/// Peta 152 fitur PRD v3.1 beserta statusnya — dipakai layar "Semua Fitur".
///
/// Sumber: PRD_PERSONAL_LIFE_OS_MASTER_v3.1.md + SISA_FITUR_PRD_v3_1.md,
/// ditambah pekerjaan Ron 19–21 Sep 2026. Ditandai JUJUR: SELESAI hanya
/// untuk yang ada kode + uji dan sudah diverifikasi.
library;

enum StatusFitur { selesai, sebagian, belum }

class ButirFitur {
  const ButirFitur({
    required this.id,
    required this.nama,
    required this.modul,
    required this.fase,
    required this.status,
    this.catatan = '',
    this.rincian = '',
    this.rute,
  });

  final String id;
  final String nama;
  final String modul;
  final String fase;
  final StatusFitur status;
  final String catatan;

  /// Keterangan panjang dari PRD (ditampilkan saat butir dibuka).
  final String rincian;

  /// Rute layar, bila fiturnya sudah punya layar di aplikasi.
  final String? rute;
}

/// Seluruh butir PRD, urut per modul lalu per nomor fitur.
const List<ButirFitur> petaFitur = <ButirFitur>[
  ButirFitur(
    id: 'FR-01',
    nama: 'Tambah tagihan: nama, jumlah, jatuh tempo (tanggal; opsi "setiap',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-02',
    nama: 'Template cepat tagihan Indonesia: Listrik PLN, Air PDAM, Internet/',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-03',
    nama: 'Frekuensi: sekali, mingguan, 2-mingguan, bulanan, 2-bulanan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    rincian: 'Frekuensi: sekali, mingguan, 2-mingguan, bulanan, 2-bulanan,',
  ),
  ButirFitur(
    id: 'FR-04',
    nama: 'Tagihan berulang otomatis membuat entri periode berikutnya saat',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-05',
    nama: 'Edit & hapus; penghapusan menanyakan konfirmasi & menawarkan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-06',
    nama: 'Status: Belum Bayar / Lunas (+tanggal bayar) / Terlambat',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-07',
    nama: 'Pencarian & filter (kategori, status, bulan)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Ron 21 Sep: kotak pencarian (nama/catatan) + saringan bulan (termasuk bulan mendatang) + status terlambat.',
    rincian: 'Pencarian & filter (kategori, status, bulan).',
    rute: '/tagihan',
  ),
  ButirFitur(
    id: 'FR-08',
    nama: 'Kategori kustom + ikon & warna per kategori',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'layar `/tagihan/kategori`, uji 29/29. Kolom `warna` = teks `#RRGGBB` (tanpa migrasi).',
    rincian: 'Kategori kustom + ikon & warna per kategori.',
  ),
  ButirFitur(
    id: 'FR-09',
    nama: 'Duplikasi cepat tagihan (salin sebagai template pribadi)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Duplikasi cepat tagihan (salin sebagai template pribadi).',
  ),
  ButirFitur(
    id: 'FR-10',
    nama: 'Lead time kustom per tagihan: H-7 / H-3 / H-1 / hari-H / kustom',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-11',
    nama: 'Aksi dari notifikasi: "✓ Sudah bayar" (tanpa buka aplikasi)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    rincian: 'Aksi dari notifikasi: "✓ Sudah bayar" (tanpa buka aplikasi),',
  ),
  ButirFitur(
    id: 'FR-12',
    nama: 'Anti-bising: maksimum N notifikasi per tagihan per siklus',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    rincian: 'Anti-bising: maksimum N notifikasi per tagihan per siklus;',
  ),
  ButirFitur(
    id: 'FR-13',
    nama: 'Notifikasi terkirim walau aplikasi tertutup',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-14',
    nama: 'Kanal notifikasi: Tagihan (wajib), Terlambat (urgent), Ringkasan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    rincian: 'Kanal notifikasi: Tagihan (wajib), Terlambat (urgent), Ringkasan.',
  ),
  ButirFitur(
    id: 'FR-15',
    nama: 'Ringkasan mingguan (setiap Senin pagi): daftar tagihan 7 hari ke',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-16',
    nama: 'Notifikasi "tagihan terlambat" sekali per hari hingga dibayar',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    rincian: 'Notifikasi "tagihan terlambat" sekali per hari hingga dibayar.',
  ),
  ButirFitur(
    id: 'FR-17',
    nama: 'Pengingat pintar berbasis pola: bila pengguna biasanya bayar',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
  ),
  ButirFitur(
    id: 'FR-18',
    nama: '4 tab utama: Ringkasan (hari ini/7 hari/menyusul + uang',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-19',
    nama: 'Kartu ringkasan: total tagihan bulan berjalan, total belum bayar',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    rincian: 'Kartu ringkasan: total tagihan bulan berjalan, total belum bayar,',
  ),
  ButirFitur(
    id: 'FR-20',
    nama: 'Input pemasukan bulanan opsional untuk menghitung "uang tersisa"',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    rincian: 'Input pemasukan bulanan opsional untuk menghitung "uang tersisa".',
  ),
  ButirFitur(
    id: 'FR-21',
    nama: 'Mode gelap & terang, aksent warna, ukuran teks mengikuti sistem',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: mode terang/gelap/ikut sistem + saklar di Pengaturan.',
    rincian: 'Mode gelap & terang, aksent warna, ukuran teks mengikuti sistem.',
    rute: '/pengaturan',
  ),
  ButirFitur(
    id: 'FR-22',
    nama: 'Badge/angka tagihan hari ini di ikon launcher (bila API',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
  ),
  ButirFitur(
    id: 'FR-23',
    nama: 'Semua data lokal (SQLite), tanpa akun, tanpa telemetri wajib',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Diperbarui 21 Sep: data tetap lokal; akun kini OPSIONAL untuk sinkron (FR-150).',
    rincian: 'Semua data lokal (SQLite), tanpa akun, tanpa telemetri wajib.',
  ),
  ButirFitur(
    id: 'FR-24',
    nama: 'Ekspor cadangan JSON + impor restore (termasuk migrasi antar HP)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: '`lib/core/backup/ekspor_impor.dart`, `lib/features/pengaturan/backup_screen.dart`, uji 28/28. Batas: pemilihan berkas hanya dari folder dokumen aplikasi; berkas tidak dienkripsi.',
    rincian: 'Ekspor cadangan JSON + impor restore (termasuk migrasi antar HP).',
    rute: '/cadangan',
  ),
  ButirFitur(
    id: 'FR-25',
    nama: 'Ekspor CSV untuk dibuka di spreadsheet',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Ron 21 Sep: ekspor CSV tagihan & riwayat pembayaran (menu Uang → Ekspor CSV), uji 8 kasus.',
    rincian: 'Ekspor CSV untuk dibuka di spreadsheet.',
    rute: '/tagihan/ekspor-csv',
  ),
  ButirFitur(
    id: 'FR-26',
    nama: 'Kunci aplikasi (PIN/pola/biometrik) untuk data sensitif',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Kunci aplikasi (PIN/pola/biometrik) untuk data sensitif.',
  ),
  ButirFitur(
    id: 'FR-27',
    nama: 'Sinkronisasi antar perangkat via file/cloud pilihan pengguna',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
  ),
  ButirFitur(
    id: 'FR-28',
    nama: 'Grafik sederhana beban tagihan per bulan (total & per kategori)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: '`lib/core/laporan/beban_tagihan.dart` + layar + rute `/laporan/beban-tagihan`, uji 24/24.',
    rincian: 'Grafik sederhana beban tagihan per bulan (total & per kategori).',
    rute: '/laporan/beban-tagihan',
  ),
  ButirFitur(
    id: 'FR-29',
    nama: 'Riwayat pembayaran & statistik: rata-rata nominal, jumlah',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Ron 21 Sep: statistik pembayaran — total, rata-rata, terbesar/terkecil, % tepat waktu, tren 12 bulan.',
    rute: '/laporan/statistik-pembayaran',
  ),
  ButirFitur(
    id: 'FR-30',
    nama: 'Proyeksi arus kas 3 bulan ke depan (terinspirasi PocketSmith/',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Ron 21 Sep: proyeksi arus kas 3 bulan (tagihan semua frekuensi + langganan aktif), uji 8 kasus.',
    rute: '/laporan/proyeksi-arus-kas',
  ),
  ButirFitur(
    id: 'FR-31',
    nama: 'Widget layar utama: tagihan 7 hari ke depan + total; tap membuka detai',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Widget layar utama: tagihan 7 hari ke depan + total; tap membuka detail tagihan (F01).',
  ),
  ButirFitur(
    id: 'FR-32',
    nama: 'Ringkasan harian pagi (toggle): tagihan hari ini & besok + total (F02)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.sebagian,
    rincian: 'Ringkasan harian pagi (toggle): tagihan hari ini & besok + total (F02).',
  ),
  ButirFitur(
    id: 'FR-33',
    nama: '"Uang aman sampai gajian": input tanggal gajian & saldo opsional → pro',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Ron 21 Sep: uang aman sampai gajian — tanggal gajian + saldo opsional, tagihan lewat jatuh tempo tetap dihitung.',
    rincian: '"Uang aman sampai gajian": input tanggal gajian & saldo opsional → proyeksi saldo setelah tagihan bulan berjal…',
    rute: '/uang/aman-sampai-gajian',
  ),
  ButirFitur(
    id: 'FR-34',
    nama: 'Kalkulator denda terhindarkan: estimasi denda/bunga yang dihindari tia',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Ron 21 Sep: kalkulator denda terhindarkan (aturan denda per tagihan: persen/bulan atau nominal tetap).',
    rincian: 'Kalkulator denda terhindarkan: estimasi denda/bunga yang dihindari tiap pelunasan tepat waktu + total bulanan …',
    rute: '/laporan/denda-terhindarkan',
  ),
  ButirFitur(
    id: 'FR-35',
    nama: 'Deteksi kenaikan tagihan: pembandingan nominal terhadap rata-rata 3 bu',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Ron 21 Sep: deteksi kenaikan tagihan — nominal terakhir vs rata-rata 3 sebelumnya, berikut buktinya.',
    rincian: 'Deteksi kenaikan tagihan: pembandingan nominal terhadap rata-rata 3 bulan; peringatan anomali (F05).',
    rute: '/laporan/kenaikan-tagihan',
  ),
  ButirFitur(
    id: 'FR-36',
    nama: 'Skor Disiplin Tagihan lokal (0–100) + streak bebas denda + daftar capa',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
    catatan: 'Ron 21 Sep: skor disiplin tagihan lokal 0–100 + rentetan & capaian, dengan penegasan bukan skor kredit.',
    rincian: 'Skor Disiplin Tagihan lokal (0–100) + streak bebas denda + daftar capaian; disclaimer "bukan skor kredit" (F06…',
    rute: '/laporan/skor-disiplin',
  ),
  ButirFitur(
    id: 'FR-37',
    nama: 'Rekap Tahunan ala "Wrapped": statistik tahunan + kartu berbagi gambar ',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Rekap Tahunan ala "Wrapped": statistik tahunan + kartu berbagi gambar (F07).',
  ),
  ButirFitur(
    id: 'FR-38',
    nama: 'Impor tagihan dari foto/screenshot dengan OCR di perangkat; isi kolom ',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Impor tagihan dari foto/screenshot dengan OCR di perangkat; isi kolom otomatis + konfirmasi pengguna (F08).',
  ),
  ButirFitur(
    id: 'FR-39',
    nama: 'Pemindai SMS/notifikasi bank on-device (opt-in): deteksi pembayaran ta',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Pemindai SMS/notifikasi bank on-device (opt-in): deteksi pembayaran tagihan & saldo; tanpa cloud; alur izin …',
  ),
  ButirFitur(
    id: 'FR-40',
    nama: 'Pembelajaran pola tanggal bayar dari riwayat; usul penyesuaian penging',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Pembelajaran pola tanggal bayar dari riwayat; usul penyesuaian pengingat (F10).',
  ),
  ButirFitur(
    id: 'FR-41',
    nama: 'Ekspor tagihan mendatang ke Google Kalender; opsi impor .ics (F11)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Ekspor tagihan mendatang ke Google Kalender; opsi impor .ics (F11).',
  ),
  ButirFitur(
    id: 'FR-42',
    nama: 'Pusat Bayar: preferensi aplikasi bayar per tagihan, salin nomor VA/QRI',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Pusat Bayar: preferensi aplikasi bayar per tagihan, salin nomor VA/QRIS, catatan konfirmasi pembayaran (F12).',
  ),
  ButirFitur(
    id: 'FR-43',
    nama: 'Mode Rumah Tangga: kode undangan tanpa akun, tagihan bersama, notifika',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Mode Rumah Tangga: kode undangan tanpa akun, tagihan bersama, notifikasi ke semua anggota, riwayat "siapa baya…',
  ),
  ButirFitur(
    id: 'FR-44',
    nama: 'Multi-profil terpisah (pribadi/keluarga/usaha)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Multi-profil terpisah (pribadi/keluarga/usaha) — kandidat Premium (F14).',
  ),
  ButirFitur(
    id: 'FR-45',
    nama: 'Laporan bulanan PDF/Excel + tombol bagikan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Laporan bulanan PDF/Excel + tombol bagikan — kandidat Premium (F15).',
  ),
  ButirFitur(
    id: 'FR-46',
    nama: 'Deteksi langganan duplikat & tagihan yang berhenti muncul (F16)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Deteksi langganan duplikat & tagihan yang berhenti muncul (F16).',
  ),
  ButirFitur(
    id: 'FR-47',
    nama: 'v2',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'v2 — perluas FR-43',
  ),
  ButirFitur(
    id: 'FR-48',
    nama: 'v2',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'v2 — perkuat FR-33/FR-30',
  ),
  ButirFitur(
    id: 'FR-49',
    nama: 'Pengingat Multi-Kanal',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'Pengingat Multi-Kanal — WhatsApp first: saat pengingat',
  ),
  ButirFitur(
    id: 'FR-50',
    nama: 'v2',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'v2 — perluas FR-38',
  ),
  ButirFitur(
    id: 'FR-51',
    nama: 'Catatan Kas & Utang Informal (cash ledger):',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
  ),
  ButirFitur(
    id: 'FR-52',
    nama: 'Multi-Mata Uang & Konversi: setiap tagihan memakai',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
  ),
  ButirFitur(
    id: 'FR-53',
    nama: 'Document Vault & Masa Berlaku: dokumen (STNK, pajak',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
  ),
  ButirFitur(
    id: 'FR-54',
    nama: 'Modul Kesehatan (opsional): pengingat obat/suplemen',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
  ),
  ButirFitur(
    id: 'FR-55',
    nama: 'v2',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'v2 — perluas FR-49',
  ),
  ButirFitur(
    id: 'FR-56',
    nama: 'Sub-Akses Keluarga (opsional sinkron): berbagi',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
  ),
  ButirFitur(
    id: 'FR-57',
    nama: 'F8 kandidat',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'F8 kandidat — engine sama dgn FR-03, biaya rendah',
  ),
  ButirFitur(
    id: 'FR-58',
    nama: 'F8 kandidat',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'F8 kandidat — bertahap',
  ),
  ButirFitur(
    id: 'FR-59',
    nama: 'F8 kandidat',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.belum,
    rincian: 'F8 kandidat — perluas FR-39',
  ),
  ButirFitur(
    id: 'FR-60',
    nama: 'Today (Life Command Center)',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    rincian: 'Today (Life Command Center) — satu layar: sapaan, daftar agenda hari ini (tagihan, obat, janji, tugas, ibadah), urut waktu, warna prioritas (merah/oranye/kuning/hijau)',
  ),
  ButirFitur(
    id: 'FR-61',
    nama: 'Kartu Pilar Harian',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    rincian: 'Kartu Pilar Harian — 5 ringkasan: Health, Money, Productivity, Family, Ibadah (angka ringkas, bukan nilai moral)',
  ),
  ButirFitur(
    id: 'FR-62',
    nama: 'Attention / Perhatian',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    rincian: 'Attention / Perhatian — daftar hal yang butuh tindakan: tagihan < 3 hari, pengeluaran menyimpang, dokumen hampir kedaluwarsa, obat habis, kebiasaan tertinggal',
  ),
  ButirFitur(
    id: 'FR-63',
    nama: 'Morning Briefing',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'fondasi notifikasi sudah digabung; layar Pengingat Ibadah + adaptor + pengiriman otomatis 06:00 terpasang. Uji 20/20.',
    rincian: 'Morning Briefing — ringkasan pagi (bisa dimatikan), satu layar: agenda, tagihan terdekat, cuaca (opsional, online), jadwal sholat (bila modul aktif)',
  ),
  ButirFitur(
    id: 'FR-64',
    nama: 'Evening Review',
    modul: '1 · Today / Pusat Harian',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: tinjauan malam + satu pertanyaan refleksi, bisa dimatikan (uji 9 kasus).',
    rincian: 'Evening Review — ringkasan malam: apa yang selesai, apa yang belum, satu pertanyaan refleksi',
  ),
  ButirFitur(
    id: 'FR-65',
    nama: 'Sinkron agenda Today ↔ Kalender',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: uji silang Today ↔ Kalender ↔ Kalender Keuangan lulus.',
    rincian: 'Sinkron agenda Today ↔ Kalender — Today, Kalender, dan Kalender Keuangan memakai sumber data yang sama',
  ),
  ButirFitur(
    id: 'FR-66',
    nama: 'Mode sorot "hari berat"',
    modul: '1 · Today / Pusat Harian',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: mode sorot hari berat + tunda pengingat tanpa mengubah jatuh tempo.',
    rincian: 'Mode sorot "hari berat" — bila >5 kewajiban pada satu hari, tampilkan saran urutan & tawaran menunda yang tidak mendesak',
  ),
  ButirFitur(
    id: 'FR-67',
    nama: 'Bahasa & format lokal',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: format tanggal mengikuti mata uang (IDR→id_ID, MYR→ms_MY).',
    rincian: 'Bahasa & format lokal — istilah Indonesia/Malaysia, Rupiah/Ringgit, format tanggal & waktu lokal',
  ),
  ButirFitur(
    id: 'FR-68',
    nama: 'Recurring & Subscription Manager (memperluas FR-03/FR-16)',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'Langganan: daftar, siklus, jeda/berhenti, pengingat. Uji 21/21',
    rincian: 'Recurring & Subscription Manager (memperluas FR-03/FR-16) — tiap langganan: nominal, tanggal, auto-renew, kategori, status "aktif/pause"',
  ),
  ButirFitur(
    id: 'FR-69',
    nama: 'Subscription Intelligence',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: total tahunan, 5 terbesar, proyeksi 12 bulan.',
    rincian: 'Subscription Intelligence — total per bulan & per tahun, jumlah langganan, 5 terbesar, proyeksi 12 bulan',
  ),
  ButirFitur(
    id: 'FR-70',
    nama: 'Deteksi langganan duplikat / jarang dipakai / harga naik (memperluas F',
    modul: '2 · Uang (Money OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: deteksi duplikat, kenaikan tarif, langganan jarang dipakai.',
    rincian: 'Deteksi langganan duplikat / jarang dipakai / harga naik (memperluas FR-46 + FR-35)',
  ),
  ButirFitur(
    id: 'FR-71',
    nama: 'Cashflow: pemasukan & pengeluaran berkategori (memperluas FR-20)',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'Arus kas ber-kategori; rute /uang/transaksi',
    rincian: 'Cashflow: pemasukan & pengeluaran berkategori (memperluas FR-20) — kategori Indonesia (tempat tinggal, makan, transport, pendidikan, keluarga, hiburan, kesehatan, utang, belanja, bisnis, lain-lain)',
    rute: '/uang/transaksi',
  ),
  ButirFitur(
    id: 'FR-72',
    nama: 'Budget vs Actual per kategori',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'Anggaran vs realisasi per kategori; rute /uang/anggaran',
    rincian: 'Budget vs Actual per kategori — anggaran bulanan per kategori + peringatan saat terlampaui',
    rute: '/uang/anggaran',
  ),
  ButirFitur(
    id: 'FR-73',
    nama: 'Financial Calendar',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'Kalender keuangan 6 sumber; rute /kalender-keuangan; 12 uji',
    rincian: 'Financial Calendar — gabungan: pemasukan, tagihan, langganan, cicilan, utang, pengeluaran terencana dalam satu kalender',
    rute: '/kalender-keuangan',
  ),
  ButirFitur(
    id: 'FR-74',
    nama: 'Debt Manager',
    modul: '2 · Uang (Money OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'daftar kewajiban, sisa pokok, catat pembayaran pokok+bunga, jadwal; rute /uang/kewajiban. 49 uji modul uang lanjutan',
    rincian: 'Debt Manager — daftar utang: pokok, bunga, minimum bayar, tanggal jatuh tempo, sisa',
  ),
  ButirFitur(
    id: 'FR-75',
    nama: 'Debt Strategy (Avalanche / Snowball)',
    modul: '2 · Uang (Money OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'simulasi dua metode, estimasi bulan lunas + bunga, asumsi ditampilkan; rute /uang/strategi-pelunasan',
    rincian: 'Debt Strategy (Avalanche / Snowball) — simulasi: estimasi lunas (bulan), bunga terselamatkan',
  ),
  ButirFitur(
    id: 'FR-76',
    nama: 'Net Worth Tracker',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'Kekayaan bersih + tren bulanan; rute /uang/kekayaan',
    rincian: 'Net Worth Tracker — aset (kas, bank, investasi, properti, kendaraan, emas, kripto, bisnis) − kewajiban (kartu kredit, KPR, pinjaman, cicilan) + grafik tren bulanan',
    rute: '/uang/kekayaan',
  ),
  ButirFitur(
    id: 'FR-77',
    nama: 'Laporan Keuangan Bulanan (memperluas FR-45)',
    modul: '2 · Uang (Money OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'ringkasan bulan + PDF & CSV di folder dokumen aplikasi, paket pdf 3.13.0 tanpa plugin lain; 33 uji + potret f12_laporan_bulanan',
    rincian: 'Laporan Keuangan Bulanan (memperluas FR-45) — PDF/Excel: arus kas, kategori, utang, kekayaan bersih, langganan',
  ),
  ButirFitur(
    id: 'FR-78',
    nama: 'Goal → Project → Task',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'tujuan/proyek/tugas + progres; rute /aksi; 20 uji',
    rincian: 'Goal → Project → Task — tujuan punya target & progres; proyek di bawah tujuan; tugas di bawah proyek',
  ),
  ButirFitur(
    id: 'FR-79',
    nama: 'Task cepat (3 ketukan)',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'tugas cepat di tab Kerja + pintu Aksi',
    rincian: 'Task cepat (3 ketukan) — tambah tugas dalam ≤3 ketukan, dengan tanggal/jam opsional & pengulangan',
  ),
  ButirFitur(
    id: 'FR-80',
    nama: 'Habit Engine',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'kebiasaan + penanda harian; rute /aksi/kebiasaan',
    rincian: 'Habit Engine — maksimal 5 kebiasaan utama yang dipromosikan; penanda selesai harian + kalender kebiasaan',
  ),
  ButirFitur(
    id: 'FR-81',
    nama: 'Habit Recovery Score',
    modul: '3 · Aksi & Tujuan',
    fase: 'V3',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: metrik pemulihan kebiasaan, tanpa kata menghakimi.',
    rincian: 'Habit Recovery Score — metrik pemulihan (bukan streak yang menghukum)',
  ),
  ButirFitur(
    id: 'FR-82',
    nama: 'Life Planning Engine',
    modul: '3 · Aksi & Tujuan',
    fase: 'V3',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: rantai Visi → Area → Tujuan → Proyek → Tugas (skema v5).',
    rincian: 'Life Planning Engine — Vision → Area hidup → Goal → Project → Task → Habit → Hasil',
    rute: '/aksi/visi',
  ),
  ButirFitur(
    id: 'FR-83',
    nama: 'Life Maintenance Engine',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: '6 template perawatan berkala + pengingat; rute /aksi/perawatan',
    rincian: 'Life Maintenance Engine — perawatan berkala otomatis (oli, servis AC, pajak, filter, cadangan data, ulang tahun, anniversary)',
  ),
  ButirFitur(
    id: 'FR-84',
    nama: 'Sleep & Energy OS',
    modul: '3 · Aksi & Tujuan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Sleep & Energy OS — catat tidur, jam bangun, tingkat energi/fokus (1–5) + temuan pola waktu produktif',
  ),
  ButirFitur(
    id: 'FR-85',
    nama: 'Progress & konsistensi tanpa skor moral',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: konsistensi mingguan tanpa skor moral.',
    rincian: 'Progress & konsistensi tanpa skor moral — ringkasan "tercatat / belum tercatat", grafik mingguan',
  ),
  ButirFitur(
    id: 'FR-86',
    nama: 'Jadwal Sholat',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    rincian: 'Jadwal Sholat — 5 waktu sesuai lokasi; pilih lokasi otomatis atau kota manual; pilih metode perhitungan, konvensi Ashar (madhhab), dan penyesuaian menit',
    rute: '/ibadah/jadwal-sholat',
  ),
  ButirFitur(
    id: 'FR-87',
    nama: 'Adzan & Pengingat Sholat',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    catatan: 'pengingat 5 waktu (bawaan mati, bisa dinyalakan), mode sebelum/tepat/sesudah + geser menit. Uji 20/20.',
    rincian: 'Adzan & Pengingat Sholat — mode: adzan, 5 menit sebelum, saat masuk waktu, pengingat setelah waktu berjalan + pilihan suara/dering',
  ),
  ButirFitur(
    id: 'FR-88',
    nama: 'Pelacakan Sholat 5 Waktu',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    rincian: 'Pelacakan Sholat 5 Waktu — tombol cepat ✓ per waktu; status "selesai / belum tercatat"',
  ),
  ButirFitur(
    id: 'FR-89',
    nama: 'Riwayat & Konsistensi Sholat',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.belum,
    catatan: 'belum dijadwalkan; data pendukung sudah ada',
    rincian: 'Riwayat & Konsistensi Sholat — rekap mingguan/bulanan per waktu (mis. "Subuh 24/30 tercatat"), bukan skor keimanan',
  ),
  ButirFitur(
    id: 'FR-90',
    nama: 'Kalender Hijriah',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
    rincian: 'Kalender Hijriah — tanggal Hijriah + hari besar, dengan pilihan acuan kalender (mis. rujukan resmi negara/pilihan pengguna)',
    rute: '/ibadah/kalender-hijriah',
  ),
  ButirFitur(
    id: 'FR-91',
    nama: 'Ramadan Mode',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /ibadah/ramadan',
    rincian: 'Ramadan Mode — dashboard otomatis saat Ramadan: imsak, subuh, maghrib, puasa hari ini, sholat, bacaan, sedekah',
  ),
  ButirFitur(
    id: 'FR-92',
    nama: 'Pelacakan Puasa',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /ibadah/puasa',
    rincian: 'Pelacakan Puasa — Ramadan, Senin-Kamis, Ayyamul Bidh, puasa sunnah lain, qadha, custom',
  ),
  ButirFitur(
    id: 'FR-93',
    nama: 'Pelacakan Quran',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /ibadah/quran + kartu progres di briefing pagi',
    rincian: 'Pelacakan Quran — bacaan, mendengar, hafalan, murajaah + target harian (mis. 1 halaman/hari)',
  ),
  ButirFitur(
    id: 'FR-94',
    nama: 'Pelacakan Hafalan (Hifz)',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Pelacakan Hafalan (Hifz) — per juz/surah: baru, murajaah, perlu diulang',
  ),
  ButirFitur(
    id: 'FR-95',
    nama: 'Dzikir & Doa',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /ibadah/dzikir; 4 adhkar pagi bisa ditandai dari FR-99',
    rincian: 'Dzikir & Doa — pagi, petang, sebelum tidur + penghitung (mis. target 100, tercatat 67)',
  ),
  ButirFitur(
    id: 'FR-96',
    nama: 'Zakat & Sedekah',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Zakat & Sedekah — catatan infaq/sadaqah + asisten perhitungan zakat (aset, acuan nisab, pelacakan haul) sebagai alat bantu, bukan keputusan',
  ),
  ButirFitur(
    id: 'FR-97',
    nama: 'Rencana Haji & Umrah',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Rencana Haji & Umrah — target dana (terhubung Goal & Finance), daftar persiapan dokumen',
  ),
  ButirFitur(
    id: 'FR-98',
    nama: 'Arah Kiblat & Masjid Terdekat',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Arah Kiblat & Masjid Terdekat — kompas dengan kalibrasi + cadangan arah mata angin bila sensor tidak layak; daftar masjid terdekat',
  ),
  ButirFitur(
    id: 'FR-99',
    nama: 'Islamic Morning Briefing (signature)',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'kartu ibadah pagi di briefing: sapaan, progres Quran, 4 adhkar; 3 uji',
    rincian: 'Islamic Morning Briefing (signature) — Assalamualaikum, tanggal Hijriah, waktu sholat berikutnya + hitung mundur, target Quran, adhkar, agenda hari ini',
  ),
  ButirFitur(
    id: 'FR-100',
    nama: 'Islamic Evening Review & Muhasabah',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /ibadah/muhasabah',
    rincian: 'Islamic Evening Review & Muhasabah — rekap ibadah hari ini + daftar refleksi (bukan penilaian): sholat terjaga, mengingat Allah, membantu orang, menghindari hal yang disesali, belajar, bersyukur + kol',
  ),
  ButirFitur(
    id: 'FR-101',
    nama: 'Health Dashboard (tren)',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /kesehatan',
    rincian: 'Health Dashboard (tren) — berat, tekanan darah, tidur, langkah, air, olahraga, suasana hati + arah naik/turun dibanding periode sebelumnya',
  ),
  ButirFitur(
    id: 'FR-102',
    nama: 'Pencatat Aktivitas',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /kesehatan/aktivitas',
    rincian: 'Pencatat Aktivitas — jalan, lari, sepeda, renang, gym, peregangan, olahraga, aktivitas rumah (durasi/jarak)',
  ),
  ButirFitur(
    id: 'FR-103',
    nama: 'Pencatat Tidur',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /kesehatan/tidur',
    rincian: 'Pencatat Tidur — jam tidur, jam bangun, durasi, kualitas, tidur siang',
  ),
  ButirFitur(
    id: 'FR-104',
    nama: 'Berat & Ukuran Tubuh',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.belum,
    rincian: 'Berat & Ukuran Tubuh — berat, lingkar perut, lemak tubuh, IMT, massa otot, detak jantung istirahat + target',
  ),
  ButirFitur(
    id: 'FR-105',
    nama: 'Jurnal Kesehatan (angka)',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.belum,
    rincian: 'Jurnal Kesehatan (angka) — tekanan darah, detak jantung, gula darah, suhu, saturasi oksigen, kolesterol, hasil lab + catatan satuan',
  ),
  ButirFitur(
    id: 'FR-106',
    nama: 'Manajer Obat & Vitamin',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /kesehatan/obat + penanda minum',
    rincian: 'Manajer Obat & Vitamin — jadwal minum (jam & jumlah) + penanda "sudah diminum"',
  ),
  ButirFitur(
    id: 'FR-107',
    nama: 'Perkiraan Obat Habis & Pengingat Beli',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.belum,
    rincian: 'Perkiraan Obat Habis & Pengingat Beli — sisa tablet, perkiraan tanggal habis, pengingat membeli',
  ),
  ButirFitur(
    id: 'FR-108',
    nama: 'Brankas Catatan Medis',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Brankas Catatan Medis — hasil lab, pemeriksaan tahunan, resep, imunisasi, tagihan medis, catatan dokter, laporan pencitraan + pencarian',
  ),
  ButirFitur(
    id: 'FR-109',
    nama: 'Janji Dokter di Kalender',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.belum,
    rincian: 'Janji Dokter di Kalender — pemeriksaan, tes lab, kontrol + pengingat 7 hari/1 hari/2 jam',
  ),
  ButirFitur(
    id: 'FR-110',
    nama: 'Catatan Makan Ringkas (quick log)',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Catatan Makan Ringkas (quick log) — per waktu makan, daftar sederhana + penilaian mutu (baik/cukup/kurang)',
  ),
  ButirFitur(
    id: 'FR-111',
    nama: 'Pencatat Air',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'tombol +250 ml / +500 ml',
    rincian: 'Pencatat Air — target harian + tombol +250 ml / +500 ml',
  ),
  ButirFitur(
    id: 'FR-112',
    nama: 'Jurnal Suasana Hati & Stres',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.belum,
    rincian: 'Jurnal Suasana Hati & Stres — pilihan suasana hati, tingkat energi & stres (1–5), catatan bebas',
  ),
  ButirFitur(
    id: 'FR-113',
    nama: 'Mesin Temuan Kesehatan (insight)',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Mesin Temuan Kesehatan (insight) — menghubungkan tidur ↔ suasana hati ↔ aktivitas ↔ berat, dalam bahasa netral',
  ),
  ButirFitur(
    id: 'FR-114',
    nama: 'Peringatan Dini (watch)',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Peringatan Dini (watch) — mis. berat naik 4 minggu berturut-turut, tidur di bawah kebiasaan, aktivitas menurun 14 hari',
  ),
  ButirFitur(
    id: 'FR-115',
    nama: 'Mode Kunjungan Dokter',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Mode Kunjungan Dokter — satu halaman ringkasan 30 hari (berat, tekanan darah, tidur, aktivitas, suasana hati, keluhan) yang bisa dicetak',
  ),
  ButirFitur(
    id: 'FR-116',
    nama: 'Laporan Kesehatan Bulanan',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Laporan Kesehatan Bulanan — perubahan berat/aktivitas/tidur/air/kebiasaan + "yang membaik, yang berubah, yang perlu perhatian"',
  ),
  ButirFitur(
    id: 'FR-117',
    nama: 'Profil Kesehatan & Kartu Darurat',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.belum,
    rincian: 'Profil Kesehatan & Kartu Darurat — profil (golongan darah, alergi, kondisi, obat, kontak darurat) + kartu darurat yang bisa dibuka tanpa internet & tanpa membuka seluruh aplikasi',
  ),
  ButirFitur(
    id: 'FR-118',
    nama: 'Catatan & Ide',
    modul: '6 · Pengetahuan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Catatan & Ide — simpan catatan, kutipan, tautan, foto, rekaman suara, tag; pencarian cepat',
  ),
  ButirFitur(
    id: 'FR-119',
    nama: 'Jurnal Keputusan (Decision OS)',
    modul: '6 · Pengetahuan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Jurnal Keputusan (Decision OS) — keputusan: pilihan, alasan, risiko, biaya, hasil yang diharapkan, tenggat keputusan, keputusan final, tinjauan hasil 3/6/12 bulan',
  ),
  ButirFitur(
    id: 'FR-120',
    nama: 'Pelacakan Pembelajaran',
    modul: '6 · Pengetahuan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Pelacakan Pembelajaran — kursus, keahlian, jam belajar, tingkat penguasaan',
  ),
  ButirFitur(
    id: 'FR-121',
    nama: 'Pengulangan Berkala (spaced repetition)',
    modul: '6 · Pengetahuan',
    fase: 'V4',
    status: StatusFitur.belum,
    rincian: 'Pengulangan Berkala (spaced repetition) — jadwal ulangan untuk hafalan/kosakata/istilah',
  ),
  ButirFitur(
    id: 'FR-122',
    nama: 'Pelacakan Buku & Bacaan',
    modul: '6 · Pengetahuan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Pelacakan Buku & Bacaan — daftar baca, sedang dibaca, selesai + catatan & kutipan',
  ),
  ButirFitur(
    id: 'FR-123',
    nama: 'Penghubung Pengetahuan',
    modul: '6 · Pengetahuan',
    fase: 'V4',
    status: StatusFitur.belum,
    rincian: 'Penghubung Pengetahuan — tautkan catatan ↔ tujuan ↔ proyek ↔ tugas ↔ dokumen',
  ),
  ButirFitur(
    id: 'FR-124',
    nama: 'Daftar Aset',
    modul: '7 · Rumah & Aset',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Daftar Aset — rumah, kendaraan, perangkat, furnitur, elektronik: tanggal beli, harga, nomor seri, garansi',
  ),
  ButirFitur(
    id: 'FR-125',
    nama: 'Jadwal & Riwayat Perawatan Aset',
    modul: '7 · Rumah & Aset',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Jadwal & Riwayat Perawatan Aset — servis berkala (oli, AC, tandon, filter), riwayat perbaikan, biaya',
  ),
  ButirFitur(
    id: 'FR-126',
    nama: 'Garansi & Invoice',
    modul: '7 · Rumah & Aset',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Garansi & Invoice — lampiran berkas/struk per aset + pengingat berakhirnya garansi',
  ),
  ButirFitur(
    id: 'FR-127',
    nama: 'Perkiraan Umur Pakai & Penggantian',
    modul: '7 · Rumah & Aset',
    fase: 'V4',
    status: StatusFitur.belum,
    rincian: 'Perkiraan Umur Pakai & Penggantian — estimasi masa guna + saran waktu pemeriksaan/penggantian',
  ),
  ButirFitur(
    id: 'FR-128',
    nama: 'Brankas Dokumen & Masa Berlaku (memperluas FR-53)',
    modul: '8 · Dokumen',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'dengan catatan (daftar + masa berlaku + nama berkas; enkripsi berkas BELUM — layar menuliskan itu apa adanya',
    rincian: 'Brankas Dokumen & Masa Berlaku (memperluas FR-53) — KTP, KK, paspor, SIM, STNK, sertifikat, ijazah, kontrak, polis, dokumen anak + tanggal berlaku/ perpanjangan',
    rute: '/dokumen',
  ),
  ButirFitur(
    id: 'FR-129',
    nama: 'Pengingat Perpanjangan Berlapis',
    modul: '8 · Dokumen',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'lead 90/30/7/1 hari, bisa diubah; terdaftar di isolate utama & latar',
    rincian: 'Pengingat Perpanjangan Berlapis — H-90 / H-30 / H-7 / H-1 + tombol "sudah diperpanjang" yang memperbarui masa berlaku',
  ),
  ButirFitur(
    id: 'FR-130',
    nama: 'Salin Cepat & Bagikan Terkendali',
    modul: '8 · Dokumen',
    fase: 'V2',
    status: StatusFitur.belum,
    rincian: 'Salin Cepat & Bagikan Terkendali — salin nomor paspor/KTP/KK tanpa membuka galeri; bagikan satu berkas dengan penyamaran bagian sensitif',
  ),
  ButirFitur(
    id: 'FR-131',
    nama: 'Anggota Keluarga & Tanggung Jawab',
    modul: '9 · Keluarga',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Anggota Keluarga & Tanggung Jawab — tiap item punya pemilik & penanggung jawab (mis. tagihan sekolah: pemilik anak, penanggung jawab pasangan)',
  ),
  ButirFitur(
    id: 'FR-132',
    nama: 'Kalender Keluarga',
    modul: '9 · Keluarga',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Kalender Keluarga — agenda bersama, ulang tahun, anniversary, kegiatan sekolah anak dalam satu tampilan',
  ),
  ButirFitur(
    id: 'FR-133',
    nama: 'Kas & Tanggung Jawab Rumah Tangga (memperluas FR-43 & FR-47)',
    modul: '9 · Keluarga',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Kas & Tanggung Jawab Rumah Tangga (memperluas FR-43 & FR-47) — "siapa bayar apa", pengingat halus satu ketukan, catatan pelunasan',
  ),
  ButirFitur(
    id: 'FR-134',
    nama: 'Perencanaan Perjalanan',
    modul: '10 · Perjalanan',
    fase: 'V4',
    status: StatusFitur.belum,
    rincian: 'Perencanaan Perjalanan — itinerary, tiket, hotel, anggaran, daftar bawaan, dokumen, pengingat keberangkatan',
  ),
  ButirFitur(
    id: 'FR-135',
    nama: 'Jurnal Perjalanan',
    modul: '10 · Perjalanan',
    fase: 'V4',
    status: StatusFitur.belum,
    rincian: 'Jurnal Perjalanan — foto, pengeluaran, tempat, penilaian, kenangan',
  ),
  ButirFitur(
    id: 'FR-136',
    nama: 'Backup & Restore penuh (memperluas FR-24)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'format cadangan otomatis mencakup 23 tabel baru v4; skema lebih baru ditolak',
    rincian: 'Backup & Restore penuh (memperluas FR-24) — JSON + berkas lampiran, dengan pratinjau isi backup sebelum restore',
  ),
  ButirFitur(
    id: 'FR-137',
    nama: 'Cadangan Otomatis + Rotasi + Cek Integritas',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'dengan catatan (saklar bawaan MATI; berjalan saat aplikasi dibuka, bukan penjadwal OS; rotasi hanya menghapus berkas yang dicatatnya sendiri; 10 uji',
    rincian: 'Cadangan Otomatis + Rotasi + Cek Integritas — cadangan berkala, simpan N salinan terakhir, periksa keutuhan database',
  ),
  ButirFitur(
    id: 'FR-138',
    nama: 'Audit Log Pengguna',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'Ron 20 Sep: catatan aktivitas mencakup uang, kategori, langganan, kesehatan.',
    rincian: 'Audit Log Pengguna — catatan perubahan penting: "22:31 tagihan #18 ditandai lunas", "nominal diubah 300.000 → 325.000", "pengingat ditunda sampai 23:30"',
    rute: '/audit',
  ),
  ButirFitur(
    id: 'FR-139',
    nama: 'Search Everything (signature)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'satu kotak cari lintas tabel; rute /cari; 15 uji',
    rincian: 'Search Everything (signature) — satu kotak mencari tagihan, pembayaran, tugas, catatan, dokumen, jurnal, janji',
  ),
  ButirFitur(
    id: 'FR-140',
    nama: 'Life Timeline (signature)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Life Timeline (signature) — seluruh kejadian hidup tersusun per hari/bulan/tahun, dapat dicari & disaring per modul',
  ),
  ButirFitur(
    id: 'FR-141',
    nama: 'Personal Analytics',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Personal Analytics — ringkasan lintas modul untuk 7/30/90 hari dan 1 tahun',
  ),
  ButirFitur(
    id: 'FR-142',
    nama: 'Smart Insights',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Smart Insights — temuan lintas modul: pengeluaran menyimpang, langganan jarang dipakai, titik saldo terendah, sebaran jatuh tempo ("73% tagihan jatuh pada minggu terakhir")',
  ),
  ButirFitur(
    id: 'FR-143',
    nama: 'Forecast',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.belum,
    rincian: 'Forecast — proyeksi saldo beberapa bulan, perkiraan keterlambatan proyek, tabrakan tenggat',
  ),
  ButirFitur(
    id: 'FR-144',
    nama: 'Weekly Life Review',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Weekly Life Review — rekap mingguan per pilar: apa yang membaik, apa yang perlu perhatian, fokus minggu depan',
  ),
  ButirFitur(
    id: 'FR-145',
    nama: 'Monthly Life Report (signature)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.belum,
    rincian: 'Monthly Life Report (signature) — laporan bulanan: keuangan, tagihan, tujuan, tugas, langganan, kekayaan bersih + "apa yang membaik / berubah / perlu perhatian"',
  ),
  ButirFitur(
    id: 'FR-146',
    nama: 'Annual Life Review',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.belum,
    rincian: 'Annual Life Review — "Your Year in Life": capaian, kebiasaan, keuangan, kesehatan, ibadah',
  ),
  ButirFitur(
    id: 'FR-147',
    nama: 'Notification Center',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: 'rute /notifikasi: riwayat + tingkat + tanda selesai',
    rincian: 'Notification Center — riwayat notifikasi dengan tingkat (mendesak/penting/biasa) + tanda selesai',
  ),
  ButirFitur(
    id: 'FR-148',
    nama: 'Snooze & Reschedule Engine (memperluas FR-11 & memperbaiki PB-04)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
    catatan: '15 menit/1 jam/3 jam/besok 09:00; tercatat di audit',
    rincian: 'Snooze & Reschedule Engine (memperluas FR-11 & memperbaiki PB-04) — 15 menit, 1 jam, 3 jam, besok, akhir pekan, kustom; jatuh tempo asli tidak berubah',
  ),
  ButirFitur(
    id: 'FR-149',
    nama: 'AI Copilot ber-konteks',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.belum,
    rincian: 'AI Copilot ber-konteks — tanya jawab atas data sendiri ("apa yang harus saya prioritaskan besok?"), dengan izin eksplisit & penjelasan data apa yang dikirim',
  ),
  ButirFitur(
    id: 'FR-150',
    nama: 'Sinkron Antar Perangkat & Cloud (memperluas FR-27)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.sebagian,
    catatan: 'Ron 21 Sep: akun + server sinkron jalan, TAGIHAN sudah tersinkron; modul lain belum.',
    rincian: 'Sinkron Antar Perangkat & Cloud (memperluas FR-27) — sinkron opsional, terenkripsi, pilihan penyedia atau server sendiri',
    rute: '/akun',
  ),
  ButirFitur(
    id: 'FR-151',
    nama: 'Widget & Akses Cepat Lanjutan (memperluas FR-31)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.belum,
    rincian: 'Widget & Akses Cepat Lanjutan (memperluas FR-31) — widget Today interaktif (aksi langsung), aksi cepat ikon, tombol panel cepat',
  ),
  ButirFitur(
    id: 'FR-152',
    nama: 'Multi-bahasa & Multi-mata Uang (memperluas FR-52)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.belum,
    rincian: 'Multi-bahasa & Multi-mata Uang (memperluas FR-52) — Indonesia, Melayu, Inggris + Rupiah/Ringgit/USD',
  ),
];

/// Ringkasan jumlah per status (dihitung dari daftar di atas).
Map<StatusFitur, int> ringkasanPetaFitur() {
  final hasil = <StatusFitur, int>{
    StatusFitur.selesai: 0,
    StatusFitur.sebagian: 0,
    StatusFitur.belum: 0,
  };
  for (final b in petaFitur) {
    hasil[b.status] = (hasil[b.status] ?? 0) + 1;
  }
  return hasil;
}

