/// Peta 152 fitur PRD v3.1 beserta statusnya — dipakai layar "Semua Fitur".
///
/// Sumber: PRD_PERSONAL_LIFE_OS_MASTER_v3.1.md + SISA_FITUR_PRD_v3_1.md,
/// ditambah pekerjaan Ron 19–21 Sep 2026. Ditandai JUJUR: SELESAI hanya
/// untuk yang ada kode + uji dan sudah diverifikasi.
library;

enum StatusFitur { selesai, sebagian, belum }

class ButirFitur {
  const ButirFitur({
    required this.id,
    required this.nama,
    required this.modul,
    required this.fase,
    required this.status,
    this.catatan = '',
    this.rincian = '',
    this.rute,
  });

  final String id;
  final String nama;
  final String modul;
  final String fase;
  final StatusFitur status;
  final String catatan;

  /// Keterangan panjang dari PRD (ditampilkan saat butir dibuka).
  final String rincian;

  /// Rute layar, bila fiturnya sudah punya layar di aplikasi.
  final String? rute;
}

/// Seluruh butir PRD, urut per modul lalu per nomor fitur.
const List<ButirFitur> petaFitur = <ButirFitur>[
  ButirFitur(
    id: 'FR-01',
 nama: 'Tambah tagihan: nama, jumlah, jatuh tempo (tanggal; opsi "setiap',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-02',
 nama: 'Template cepat tagihan Indonesia: Listrik PLN, Air PDAM, Internet/',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-03',
 nama: 'Frekuensi: sekali, mingguan, 2-mingguan, bulanan, 2-bulanan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Frekuensi: sekali, mingguan, 2-mingguan, bulanan, 2-bulanan,',
  ),
  ButirFitur(
    id: 'FR-04',
 nama: 'Tagihan berulang otomatis membuat entri periode berikutnya saat',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-05',
 nama: 'Edit & hapus; penghapusan menanyakan konfirmasi & menawarkan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-06',
 nama: 'Status: Belum Bayar / Lunas (+tanggal bayar) / Terlambat',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-07',
 nama: 'Pencarian & filter (kategori, status, bulan)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'kotak pencarian (nama/catatan) + saringan bulan (termasuk bulan mendatang) + status terlambat.',
 rincian: 'Pencarian & filter (kategori, status, bulan).',
    rute: '/tagihan',
  ),
  ButirFitur(
    id: 'FR-08',
 nama: 'Kategori kustom + ikon & warna per kategori',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'layar `/tagihan/kategori`, uji 29/29. Kolom `warna` = teks `#RRGGBB` (tanpa migrasi).',
 rincian: 'Kategori kustom + ikon & warna per kategori.',
  ),
  ButirFitur(
    id: 'FR-09',
 nama: 'Duplikasi cepat tagihan (salin sebagai template pribadi)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'duplikat cepat tagihan + template pribadi yang tersimpan.',
 rincian: 'Duplikasi cepat tagihan (salin sebagai template pribadi).',
  ),
  ButirFitur(
    id: 'FR-10',
 nama: 'Lead time kustom per tagihan: H-7 / H-3 / H-1 / hari-H / kustom',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-11',
 nama: 'Aksi dari notifikasi: "✓ Sudah bayar" (tanpa buka aplikasi)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Aksi dari notifikasi: "✓ Sudah bayar" (tanpa buka aplikasi),',
  ),
  ButirFitur(
    id: 'FR-12',
 nama: 'Anti-bising: maksimum N notifikasi per tagihan per siklus',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Anti-bising: maksimum N notifikasi per tagihan per siklus;',
  ),
  ButirFitur(
    id: 'FR-13',
 nama: 'Notifikasi terkirim walau aplikasi tertutup',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-14',
 nama: 'Kanal notifikasi: Tagihan (wajib), Terlambat (urgent), Ringkasan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Kanal notifikasi: Tagihan (wajib), Terlambat (urgent), Ringkasan.',
  ),
  ButirFitur(
    id: 'FR-15',
 nama: 'Ringkasan mingguan (setiap Senin pagi): daftar tagihan 7 hari ke',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-16',
 nama: 'Notifikasi "tagihan terlambat" sekali per hari hingga dibayar',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Notifikasi "tagihan terlambat" sekali per hari hingga dibayar.',
  ),
  ButirFitur(
    id: 'FR-17',
 nama: 'Pengingat pintar berbasis pola: bila pengguna biasanya bayar',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'pola bayar dipelajari dari riwayat; lead pengingat disarankan aplikasi.',
    rute: '/tagihan/pola-bayar',
  ),
  ButirFitur(
    id: 'FR-18',
 nama: '4 tab utama: Ringkasan (hari ini/7 hari/menyusul + uang',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
  ),
  ButirFitur(
    id: 'FR-19',
 nama: 'Kartu ringkasan: total tagihan bulan berjalan, total belum bayar',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Kartu ringkasan: total tagihan bulan berjalan, total belum bayar,',
  ),
  ButirFitur(
    id: 'FR-20',
 nama: 'Input pemasukan bulanan opsional untuk menghitung "uang tersisa"',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Input pemasukan bulanan opsional untuk menghitung "uang tersisa".',
  ),
  ButirFitur(
    id: 'FR-21',
 nama: 'Mode gelap & terang, aksent warna, ukuran teks mengikuti sistem',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'mode terang/gelap/ikut sistem + saklar di Pengaturan.',
 rincian: 'Mode gelap & terang, aksent warna, ukuran teks mengikuti sistem.',
    rute: '/pengaturan',
  ),
  ButirFitur(
    id: 'FR-22',
 nama: 'Badge/angka tagihan hari ini di ikon launcher (bila API',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'lencana angka di ikon aplikasi = jumlah tagihan yang jatuh tempo hari ini atau sudah lewat & belum lunas; dikirim ke peluncur lewat siaran khas Samsung/Sony/HTC/LG/Nova/ADW. Peluncur yang tidak mendukung lencana tidak menampilkannya — dinyatakan di layar, bukan dijanjikan. Uji: hitungan + kanal (kanal tiruan mencatat angka yang dikirim).',
    rute: '/pengaturan/ikon-widget',

  ),
  ButirFitur(
    id: 'FR-23',
 nama: 'Semua data lokal (SQLite), tanpa akun, tanpa telemetri wajib',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'Diperbarui 21 Sep: data tetap lokal; akun kini OPSIONAL untuk sinkron.',
 rincian: 'Semua data lokal (SQLite), tanpa akun, tanpa telemetri wajib.',
  ),
  ButirFitur(
    id: 'FR-24',
 nama: 'Ekspor cadangan JSON + impor restore (termasuk migrasi antar HP)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: '`lib/core/backup/ekspor_impor.dart`, `lib/features/pengaturan/backup_screen.dart`, uji 28/28. Batas: pemilihan berkas hanya dari folder dokumen aplikasi; berkas tidak dienkripsi.',
 rincian: 'Ekspor cadangan JSON + impor restore (termasuk migrasi antar HP).',
    rute: '/cadangan',
  ),
  ButirFitur(
    id: 'FR-25',
 nama: 'Ekspor CSV untuk dibuka di spreadsheet',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'ekspor CSV tagihan & riwayat pembayaran (menu Uang → Ekspor CSV), uji 8 kasus.',
 rincian: 'Ekspor CSV untuk dibuka di spreadsheet.',
    rute: '/tagihan/ekspor-csv',
  ),
  ButirFitur(
    id: 'FR-26',
 nama: 'Kunci aplikasi (PIN/pola/biometrik) untuk data sensitif',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Kunci aplikasi (PIN/pola/biometrik) untuk data sensitif.',
 catatan: 'PIN 4-12 angka disimpan sebagai turunan PBKDF2-HMAC-SHA256 (PIN mentah tidak pernah ditulis); salah 5 kali -> percobaan ditahan 30 detik; boleh dibuka dengan kunci perangkat HP (sidik jari/PIN HP lewat Android Keyguard); tirai kunci menahan ISI aplikasi sampai PIN benar; masa tenggang sebelum terkunci lagi bisa diatur (langsung/30 dtk/1 mnt/5 mnt). Uji: 11 kasus (logika + layar).',
    rute: '/pengaturan/kunci',

  ),
  ButirFitur(
    id: 'FR-27',
 nama: 'Sinkronisasi antar perangkat via file/cloud pilihan pengguna',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'pilihan kanal sinkron — server sendiri (akun) atau BERKAS (ekspor.json lalu dibagikan lewat WhatsApp/Drive/USB, impor dari pemilih berkas Android). Tanpa server pun jalan.',
  ),
  ButirFitur(
    id: 'FR-28',
 nama: 'Grafik sederhana beban tagihan per bulan (total & per kategori)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: '`lib/core/laporan/beban_tagihan.dart` + layar + rute `/laporan/beban-tagihan`, uji 24/24.',
 rincian: 'Grafik sederhana beban tagihan per bulan (total & per kategori).',
    rute: '/laporan/beban-tagihan',
  ),
  ButirFitur(
    id: 'FR-29',
 nama: 'Riwayat pembayaran & statistik: rata-rata nominal, jumlah',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'statistik pembayaran — total, rata-rata, terbesar/terkecil, % tepat waktu, tren 12 bulan.',
    rute: '/laporan/statistik-pembayaran',
  ),
  ButirFitur(
    id: 'FR-30',
 nama: 'Proyeksi arus kas 3 bulan ke depan (terinspirasi PocketSmith/',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'proyeksi arus kas 3 bulan (tagihan semua frekuensi + langganan aktif), uji 8 kasus.',
    rute: '/laporan/proyeksi-arus-kas',
  ),
  ButirFitur(
    id: 'FR-31',
 nama: 'Widget layar utama: tagihan 7 hari ke depan + total; tap membuka detai',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Widget layar utama: tagihan 7 hari ke depan + total; tap membuka detail tagihan.',
 catatan: 'widget layar utama \'Tagihan 7 hari\' — judul (jumlah tagihan hari ini / 7 hari ke depan) + total + tiga tagihan terdekat dengan nominalnya; menekan baris membuka daftar tagihan; isi dikirim ulang setiap data tagihan berubah; bisa dinyalakan/dimatikan di Pengaturan -> Ikon & widget. Uji: penyusun isi + kanal.',
    rute: '/pengaturan/ikon-widget',

  ),
  ButirFitur(
    id: 'FR-32',
 nama: 'Ringkasan harian pagi (toggle): tagihan hari ini & besok + total',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'ringkasan pagi — tagihan hari ini, besok, dan total 7 hari.',
 rincian: 'Ringkasan harian pagi (toggle): tagihan hari ini & besok + total.',
  ),
  ButirFitur(
    id: 'FR-33',
 nama: '"Uang aman sampai gajian": input tanggal gajian & saldo opsional → pro',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'uang aman sampai gajian — tanggal gajian + saldo opsional, tagihan lewat jatuh tempo tetap dihitung.',
 rincian: '"Uang aman sampai gajian": input tanggal gajian & saldo opsional → proyeksi saldo setelah tagihan bulan berjal…',
    rute: '/uang/aman-sampai-gajian',
  ),
  ButirFitur(
    id: 'FR-34',
 nama: 'Kalkulator denda terhindarkan: estimasi denda/bunga yang dihindari tia',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'kalkulator denda terhindarkan (aturan denda per tagihan: persen/bulan atau nominal tetap).',
 rincian: 'Kalkulator denda terhindarkan: estimasi denda/bunga yang dihindari tiap pelunasan tepat waktu + total bulanan …',
    rute: '/laporan/denda-terhindarkan',
  ),
  ButirFitur(
    id: 'FR-35',
 nama: 'Deteksi kenaikan tagihan: pembandingan nominal terhadap rata-rata 3 bu',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'deteksi kenaikan tagihan — nominal terakhir vs rata-rata 3 sebelumnya, berikut buktinya.',
 rincian: 'Deteksi kenaikan tagihan: pembandingan nominal terhadap rata-rata 3 bulan; peringatan anomali.',
    rute: '/laporan/kenaikan-tagihan',
  ),
  ButirFitur(
    id: 'FR-36',
 nama: 'Skor Disiplin Tagihan lokal (0–100) + streak bebas denda + daftar capa',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'skor disiplin tagihan lokal 0–100 + rentetan & capaian, dengan penegasan bukan skor kredit.',
 rincian: 'Skor Disiplin Tagihan lokal (0–100) + streak bebas denda + daftar capaian; disclaimer "bukan skor kredit" (F06…',
    rute: '/laporan/skor-disiplin',
  ),
  ButirFitur(
    id: 'FR-37',
 nama: 'Rekap Tahunan ala "Wrapped": statistik tahunan + kartu berbagi gambar ',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'rekap tahunan (total, tepat waktu, bulan tersibuk) + kartu berbagi PNG.',
 rincian: 'Rekap Tahunan ala "Wrapped": statistik tahunan + kartu berbagi gambar.',
    rute: '/uang/rekap-tahunan',
  ),
  ButirFitur(
    id: 'FR-38',
 nama: 'Impor tagihan dari foto/screenshot dengan OCR di perangkat',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: 'F08',
    status: StatusFitur.selesai,
 rincian: 'Impor tagihan dari foto/screenshot dengan OCR di perangkat; isi '
        'kolom otomatis + konfirmasi pengguna.',
 catatan: 'OCR ML Kit dengan model TERBUNDEL (jalan tanpa '
        'internet, tanpa Play Services); foto diproses di HP dan tidak dikirim '
        'ke mana pun. Nomor pelanggan, nominal (dari baris TOTAL), dan jatuh '
        'tempo ditebak dari teks lalu ditampilkan sebagai DRAF — pengguna '
        'melengkapi & menyetujui dulu. Konsekuensi jujur: ukuran APK naik dan '
        'kualitas hasil bergantung pada foto.',
    rute: '/tagihan/impor-foto',
  ),
  ButirFitur(
    id: 'FR-39',
 nama: 'Pemindai SMS/notifikasi bank on-device (opt-in): deteksi pembayaran ta',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Pemindai SMS/notifikasi bank on-device (opt-in): deteksi '
        'pembayaran tagihan & saldo; tanpa cloud; alur izin berlapis',
 catatan: 'izin MATI secara bawaan & diminta lewat dialog '
        'sistem; penguraian berjalan di perangkat (kanal lifeos/sms); hasil '
        'hanya USULAN — tagihan tidak pernah ditandai lunas sendiri. Yang '
        'tidak dikenali disebut alasannya, bukan ditebak. Notifikasi aplikasi '
        'bank lewat notifikasi belum dibuat (sengaja tidak dikerjakan).',
    rute: '/uang/pemindai-bank',
  ),
  ButirFitur(
    id: 'FR-40',
 nama: 'Pembelajaran pola tanggal bayar dari riwayat; usul penyesuaian penging',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'pengingat pintar mengikuti pola bayar pengguna (layar Pola bayar).',
 rincian: 'Pembelajaran pola tanggal bayar dari riwayat; usul penyesuaian pengingat.',
    rute: '/tagihan/pola-bayar',
  ),
  ButirFitur(
    id: 'FR-41',
 nama: 'Ekspor tagihan mendatang ke Google Kalender; opsi impor.ics',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'ekspor jadwal tagihan ke.ics (Google Kalender), periode 3/6/12/24 bulan.',
 rincian: 'Ekspor tagihan mendatang ke Google Kalender; opsi impor.ics.',
    rute: '/tagihan/ekspor-kalender',
  ),
  ButirFitur(
    id: 'FR-42',
 nama: 'Pusat Bayar: preferensi aplikasi bayar per tagihan, salin nomor VA/QRI',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'Pusat Bayar — VA/QRIS, salin nomor sekali tekan, catatan konfirmasi.',
 rincian: 'Pusat Bayar: preferensi aplikasi bayar per tagihan, salin nomor VA/QRIS, catatan konfirmasi pembayaran.',
    rute: '/tagihan/pusat-bayar',
  ),
  ButirFitur(
    id: 'FR-43',
 nama: 'Mode Rumah Tangga: kode undangan tanpa akun, tagihan bersama, notifika',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Mode Rumah Tangga: kode undangan tanpa akun, tagihan bersama, '
        'notifikasi ke semua anggota, riwayat "siapa bayar apa"',
 catatan: 'kode undangan 6 karakter dari daftar aman (tanpa '
        'akun); anggota memakai daftar anggota keluarga yang sudah ada (tidak '
        'ada tabel orang kedua); pembagian memakai bagi rata sehingga '
        'jumlah bagian SELALU pas dengan total; pengingat hanya DISIAPKAN '
        '(disalin + tautan WhatsApp) — aplikasi tidak mengirim sendiri.',
    rute: '/rumah/mode-rumah-tangga',
  ),
  ButirFitur(
    id: 'FR-44',
 nama: 'Multi-profil terpisah (pribadi/keluarga/usaha)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 rincian: 'Multi-profil terpisah (pribadi/keluarga/usaha) — kandidat Premium.',
 catatan: 'profil pribadi/keluarga/usaha masing-masing punya BERKAS basis data SENDIRI sehingga data tidak bercampur (dibuktikan uji dengan dua basis data terpisah); profil \'Pribadi\' memakai berkas lama sehingga data pengguna yang sudah ada tidak hilang; profil aktif harus dipindah dulu sebelum dihapus; pindah profil = pindah berkas basis data. Uji: 7 kasus.',
    rute: '/pengaturan/profil',

  ),
  ButirFitur(
    id: 'FR-45',
 nama: 'Laporan bulanan PDF/Excel + tombol bagikan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'tombol bagikan laporan bulanan (PDF & CSV) lewat kanal Android sendiri.',
 rincian: 'Laporan bulanan PDF/Excel + tombol bagikan — kandidat Premium.',
    rute: '/laporan/bulanan',
  ),
  ButirFitur(
    id: 'FR-46',
 nama: 'Deteksi langganan duplikat & tagihan yang berhenti muncul',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'deteksi tagihan berulang yang berhenti muncul + bukti & matikan pengingatnya.',
 rincian: 'Deteksi langganan duplikat & tagihan yang berhenti muncul.',
    rute: '/uang/langganan',
  ),
  ButirFitur(
    id: 'FR-47',
 nama: 'Split Bill & Patungan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: 'V2',
    status: StatusFitur.selesai,
 rincian: 'Split bill & patungan: grup (kode undangan), anggota, belanja '
        'sama rata atau bagian khusus, hasil "siapa transfer ke siapa"',
 catatan: 'pembagian sama rata membagi sisa sen ke depan '
        'sehingga jumlah bagian SELALU sama dengan total (bukan dibulatkan '
        'diam-diam); hasil menandai belumBisa bila bagian belum diisi atau '
        'jumlahnya tidak sama dengan total. Tabel grup/anggota/belanja/bagian '
        'ikut mesin sinkron 150. Uji: mesin + repositori + layar.',
    rute: '/patungan',
  ),
  ButirFitur(
    id: 'FR-48',
 nama: 'Dasbor Arus Kas & Dana Persiapan',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: 'V2',
    status: StatusFitur.selesai,
 rincian: 'Dana persiapan: uang yang disisihkan untuk kebutuhan terencana '
        '(pajak, sekolah, servis, tiket pulang) + sisa & setoran per bulan + '
        'arus kas bersih',
 catatan: 'setoran per bulan dihitung dari tanggal target; bila '
        'target/tanggal belum diisi, angkanya dinyatakan belum bisa dihitung '
        '(bukan ditebak). Arus kas bersih = arus kas − alokasi bulan ini, dan '
        'peringatan muncul bila alokasi melebihi arus kas. Tabel '
        'dana_persiapan & setoran_dana ikut mesin sinkron 150. Uji: mesin + '
        'repositori + layar.',
    rute: '/laporan/dana-persiapan',
  ),
  ButirFitur(
    id: 'FR-49',
 nama: 'Pengingat Multi-Kanal',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'pengingat multi-kanal (notifikasi/WhatsApp/SMS/Telegram) + teks siap kirim. Pengiriman otomatis via WA Business belum ada (dinyatakan di layar).',
 rincian: 'Pengingat Multi-Kanal — WhatsApp first: saat pengingat',
    rute: '/tagihan/pengingat-multi-kanal',
  ),
  ButirFitur(
    id: 'FR-50',
 nama: 'Perluas impor OCR ke struk belanja & nota manual',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: 'V2',
    status: StatusFitur.selesai,
 rincian: 'v2 — perluas impor dari foto ke struk belanja & nota manual.',
 catatan: 'satu layar dengan pilihan Tagihan / Struk-Nota. '
        'Baris barang ikut terbaca (nama + harga), lalu diperiksa: bila jumlah '
        'barang tidak sama dengan TOTAL di struk, layar mengatakan '
        'selisihnya — bukan didiamkan. Hasil struk disimpan sebagai '
        'PENGELUARAN (sumber: ocr), bukan tagihan.',
    rute: '/tagihan/impor-foto',
  ),
  ButirFitur(
    id: 'FR-51',
 nama: 'Catatan Kas & Utang Informal (cash ledger):',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'catatan kas & utang informal — saldo per pihak + jatuh tempo dekat.',
    rute: '/uang/kas-informal',
  ),
  ButirFitur(
    id: 'FR-52',
 nama: 'Multi-Mata Uang & Konversi: setiap tagihan memakai',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'mata uang per tagihan + konversi; kurs diisi pengguna, sumber & tanggal ditampilkan.',
    rute: '/uang/mata-uang',
  ),
  ButirFitur(
    id: 'FR-53',
 nama: 'Document Vault & Masa Berlaku: dokumen (STNK, pajak',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'brankas dokumen + masa berlaku (Dinda) dilengkapi tombol \'salin nomor\' tanpa membuka berkas (Ron).',
    rute: '/dokumen',
  ),
  ButirFitur(
    id: 'FR-54',
 nama: 'Modul Kesehatan (opsional): pengingat obat/suplemen',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: 'V2',
    status: StatusFitur.selesai,
 rincian: 'Pengingat obat/suplemen: saklar izin, jam minum hari ini, tanda '
        'sudah minum / tunda / terlewat, dan jam berikutnya',
 catatan: 'MEMAKAI ULANG modul obat yang sudah ada (tabel obat, '
        'jadwal_obat, minum_obat + ObatRepository) — tidak ada tabel atau '
        'layar obat kedua. Pengingat MATI secara bawaan dan hanya berbunyi '
        'setelah izin dinyalakan; slot yang sudah dicatat tidak diingatkan dua '
        'kali. Uji: mesin rencana + sumber pengingat + layar.',
    rute: '/kesehatan/obat/jadwal',
  ),
  ButirFitur(
    id: 'FR-55',
 nama: 'Delegasi Cepat via WhatsApp',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: 'V2',
    status: StatusFitur.selesai,
 rincian: 'Delegasi cepat: pilih pengingat (tagihan belum lunas atau tulis '
        'sendiri), nama & nomor tujuan, teks siap kirim + tautan WhatsApp/SMS',
 catatan: 'aplikasi TIDAK mengirim pesan sendiri — hanya '
        'menyiapkan teks + tautan yang membuka WhatsApp/SMS di HP. Nomor '
        'dirapikan lewat normalisasi (tidak ditulis ulang); nomor tidak '
        'sah ditolak dengan alasan yang bisa dibaca. Tabel delegasi_pengingat '
        'ikut mesin sinkron 150. Uji: mesin + repositori + layar.',
    rute: '/tagihan/delegasi',
  ),
  ButirFitur(
    id: 'FR-56',
 nama: 'Sub-Akses Keluarga (opsional sinkron): berbagi',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: '-',
    status: StatusFitur.selesai,
 catatan: 'izin per anggota × modul; SEMUA modul mati secara '
        'bawaan dan penegakannya ada di lapisan data (bolehLihat/bolehTambah), '
        'bukan sekadar menyembunyikan menu. Paket berbagi hanya memuat daftar '
        'izin + JUMLAH baris per modul — isi catatan pribadi tidak ikut, supaya '
        'berkas yang salah kirim tidak membocorkan keuangan/kesehatan.',
    rute: '/keluarga/sub-akses',
  ),
  ButirFitur(
    id: 'FR-57',
 nama: 'Perawatan berkala (F8 kandidat)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: 'F8',
    status: StatusFitur.selesai,
 rincian: 'Perawatan berkala: jadwal berulang per aset/rumah + pengingat '
        'H-7/H-1, memakai mesin perawatan yang sama',
 catatan: 'sudah ada sejak dulu (tabel `perawatan` dengan '
        'intervalHari/berikutnya/leadHari, template bawaan, layar, dan '
        '`SumberPengingatPerawatan` yang terdaftar di isolate utama+latarbelakang). '
        'Sudah diverifikasi dan diuji — sengaja TIDAK membuat tabel '
        'atau mesin perawatan kedua.',
    rute: '/aksi/perawatan',
  ),
  ButirFitur(
    id: 'FR-58',
 nama: 'Voice & Parsing Cerdas (F8 kandidat, bertahap)',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: 'F8',
    status: StatusFitur.selesai,
 rincian: 'Satu kalimat (diucapkan atau ditulis) jadi DRAF pengeluaran/'
        'tagihan/dana/perawatan; pengguna memeriksa dulu sebelum disimpan',
 catatan: 'pengenalan suara memakai fitur bawaan Android '
        '(kanal lifeos/suara) — aplikasi hanya menerima teksnya, tidak '
        'menyimpan rekaman; penguraian nominal/tanggal berjalan di perangkat '
        'dan kalimat yang belum dikenali dijawab dengan saran, bukan ditebak. '
        'Draf dana & perawatan diarahkan ke layarnya (tidak menebak isian).',
    rute: '/suara',
  ),
  ButirFitur(
    id: 'FR-59',
 nama: 'Auto-catat pengeluaran',
    modul: '0 · Dasar & Tagihan (V1)',
    fase: 'F8',
    status: StatusFitur.sebagian,
 rincian: 'F8 kandidat — perluas pemindai bank (auto-catat pengeluaran dari pesan '
        'bank).',
 catatan: 'dari SMS bank SUDAH bisa — pesan yang cocok bisa '
        'langsung dicatat sebagai pengeluaran atau ditandai melunasi tagihan '
        '(satu ketukan, lewat /uang/pemindai-bank). Membaca NOTIFIKASI '
        'aplikasi bank SENGAJA TIDAK DIKERJAKAN atas keputusan pemilik: izin '
        'baca semua notifikasi terlalu luas/berisiko. Jadi statusnya '
        'SEBAGIAN, bukan selesai.',
  ),
  ButirFitur(
    id: 'FR-60',
 nama: 'Today (Life Command Center)',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 rincian: 'Today (Life Command Center) — satu layar: sapaan, daftar agenda hari ini (tagihan, obat, janji, tugas, ibadah), urut waktu, warna prioritas (merah/oranye/kuning/hijau)',
  ),
  ButirFitur(
    id: 'FR-61',
 nama: 'Kartu Pilar Harian',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 rincian: 'Kartu Pilar Harian — 5 ringkasan: Health, Money, Productivity, Family, Ibadah (angka ringkas, bukan nilai moral)',
  ),
  ButirFitur(
    id: 'FR-62',
 nama: 'Attention / Perhatian',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 rincian: 'Attention / Perhatian — daftar hal yang butuh tindakan: tagihan < 3 hari, pengeluaran menyimpang, dokumen hampir kedaluwarsa, obat habis, kebiasaan tertinggal',
  ),
  ButirFitur(
    id: 'FR-63',
 nama: 'Morning Briefing',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'fondasi notifikasi sudah digabung; layar Pengingat Ibadah + adaptor + pengiriman otomatis 06:00 terpasang. Uji 20/20.',
 rincian: 'Morning Briefing — ringkasan pagi (bisa dimatikan), satu layar: agenda, tagihan terdekat, cuaca (opsional, online), jadwal sholat (bila modul aktif)',
  ),
  ButirFitur(
    id: 'FR-64',
 nama: 'Evening Review',
    modul: '1 · Today / Pusat Harian',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'tinjauan malam + satu pertanyaan refleksi, bisa dimatikan (uji 9 kasus).',
 rincian: 'Evening Review — ringkasan malam: apa yang selesai, apa yang belum, satu pertanyaan refleksi',
  ),
  ButirFitur(
    id: 'FR-65',
 nama: 'Sinkron agenda Today ↔ Kalender',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'uji silang Today ↔ Kalender ↔ Kalender Keuangan lulus.',
 rincian: 'Sinkron agenda Today ↔ Kalender — Today, Kalender, dan Kalender Keuangan memakai sumber data yang sama',
  ),
  ButirFitur(
    id: 'FR-66',
 nama: 'Mode sorot "hari berat"',
    modul: '1 · Today / Pusat Harian',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'mode sorot hari berat + tunda pengingat tanpa mengubah jatuh tempo.',
 rincian: 'Mode sorot "hari berat" — bila >5 kewajiban pada satu hari, tampilkan saran urutan & tawaran menunda yang tidak mendesak',
  ),
  ButirFitur(
    id: 'FR-67',
 nama: 'Bahasa & format lokal',
    modul: '1 · Today / Pusat Harian',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'format tanggal mengikuti mata uang (IDR→id_ID, MYR→ms_MY).',
 rincian: 'Bahasa & format lokal — istilah Indonesia/Malaysia, Rupiah/Ringgit, format tanggal & waktu lokal',
  ),
  ButirFitur(
    id: 'FR-68',
 nama: 'Recurring & Subscription Manager',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'Langganan: daftar, siklus, jeda/berhenti, pengingat. Uji 21/21',
 rincian: 'Recurring & Subscription Manager — tiap langganan: nominal, tanggal, auto-renew, kategori, status "aktif/pause"',
  ),
  ButirFitur(
    id: 'FR-69',
 nama: 'Subscription Intelligence',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'total tahunan, 5 terbesar, proyeksi 12 bulan.',
 rincian: 'Subscription Intelligence — total per bulan & per tahun, jumlah langganan, 5 terbesar, proyeksi 12 bulan',
  ),
  ButirFitur(
    id: 'FR-70',
 nama: 'Deteksi langganan duplikat / jarang dipakai / harga naik (memperluas F',
    modul: '2 · Uang (Money OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'deteksi duplikat, kenaikan tarif, langganan jarang dipakai.',
 rincian: 'Deteksi langganan duplikat / jarang dipakai / harga naik',
  ),
  ButirFitur(
    id: 'FR-71',
 nama: 'Cashflow: pemasukan & pengeluaran berkategori',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'Arus kas ber-kategori; rute /uang/transaksi',
 rincian: 'Cashflow: pemasukan & pengeluaran berkategori — kategori Indonesia (tempat tinggal, makan, transport, pendidikan, keluarga, hiburan, kesehatan, utang, belanja, bisnis, lain-lain)',
    rute: '/uang/transaksi',
  ),
  ButirFitur(
    id: 'FR-72',
 nama: 'Budget vs Actual per kategori',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'Anggaran vs realisasi per kategori; rute /uang/anggaran',
 rincian: 'Budget vs Actual per kategori — anggaran bulanan per kategori + peringatan saat terlampaui',
    rute: '/uang/anggaran',
  ),
  ButirFitur(
    id: 'FR-73',
 nama: 'Financial Calendar',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'Kalender keuangan 6 sumber; rute /kalender-keuangan; 12 uji',
 rincian: 'Financial Calendar — gabungan: pemasukan, tagihan, langganan, cicilan, utang, pengeluaran terencana dalam satu kalender',
    rute: '/kalender-keuangan',
  ),
  ButirFitur(
    id: 'FR-74',
 nama: 'Debt Manager',
    modul: '2 · Uang (Money OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'daftar kewajiban, sisa pokok, catat pembayaran pokok+bunga, jadwal; rute /uang/kewajiban. 49 uji modul uang lanjutan',
 rincian: 'Debt Manager — daftar utang: pokok, bunga, minimum bayar, tanggal jatuh tempo, sisa',
  ),
  ButirFitur(
    id: 'FR-75',
 nama: 'Debt Strategy (Avalanche / Snowball)',
    modul: '2 · Uang (Money OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'simulasi dua metode, estimasi bulan lunas + bunga, asumsi ditampilkan; rute /uang/strategi-pelunasan',
 rincian: 'Debt Strategy (Avalanche / Snowball) — simulasi: estimasi lunas (bulan), bunga terselamatkan',
  ),
  ButirFitur(
    id: 'FR-76',
 nama: 'Net Worth Tracker',
    modul: '2 · Uang (Money OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'Kekayaan bersih + tren bulanan; rute /uang/kekayaan',
 rincian: 'Net Worth Tracker — aset (kas, bank, investasi, properti, kendaraan, emas, kripto, bisnis) − kewajiban (kartu kredit, KPR, pinjaman, cicilan) + grafik tren bulanan',
    rute: '/uang/kekayaan',
  ),
  ButirFitur(
    id: 'FR-77',
 nama: 'Laporan Keuangan Bulanan',
    modul: '2 · Uang (Money OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'ringkasan bulan + PDF & CSV di folder dokumen aplikasi, paket pdf 3.13.0 tanpa plugin lain; 33 uji + potret f12_laporan_bulanan',
 rincian: 'Laporan Keuangan Bulanan — PDF/Excel: arus kas, kategori, utang, kekayaan bersih, langganan',
  ),
  ButirFitur(
    id: 'FR-78',
 nama: 'Goal → Project → Task',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'tujuan/proyek/tugas + progres; rute /aksi; 20 uji',
 rincian: 'Goal → Project → Task — tujuan punya target & progres; proyek di bawah tujuan; tugas di bawah proyek',
  ),
  ButirFitur(
    id: 'FR-79',
 nama: 'Task cepat (3 ketukan)',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'tugas cepat di tab Kerja + pintu Aksi',
 rincian: 'Task cepat (3 ketukan) — tambah tugas dalam ≤3 ketukan, dengan tanggal/jam opsional & pengulangan',
  ),
  ButirFitur(
    id: 'FR-80',
 nama: 'Habit Engine',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'kebiasaan + penanda harian; rute /aksi/kebiasaan',
 rincian: 'Habit Engine — maksimal 5 kebiasaan utama yang dipromosikan; penanda selesai harian + kalender kebiasaan',
  ),
  ButirFitur(
    id: 'FR-81',
 nama: 'Habit Recovery Score',
    modul: '3 · Aksi & Tujuan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'metrik pemulihan kebiasaan, tanpa kata menghakimi.',
 rincian: 'Habit Recovery Score — metrik pemulihan (bukan streak yang menghukum)',
  ),
  ButirFitur(
    id: 'FR-82',
 nama: 'Life Planning Engine',
    modul: '3 · Aksi & Tujuan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'rantai Visi → Area → Tujuan → Proyek → Tugas (skema v5).',
 rincian: 'Life Planning Engine — Vision → Area hidup → Goal → Project → Task → Habit → Hasil',
    rute: '/aksi/visi',
  ),
  ButirFitur(
    id: 'FR-83',
 nama: 'Life Maintenance Engine',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: '6 template perawatan berkala + pengingat; rute /aksi/perawatan',
 rincian: 'Life Maintenance Engine — perawatan berkala otomatis (oli, servis AC, pajak, filter, cadangan data, ulang tahun, anniversary)',
  ),
  ButirFitur(
    id: 'FR-84',
 nama: 'Sleep & Energy OS',
    modul: '3 · Aksi & Tujuan',
    fase: 'V3',
    status: StatusFitur.selesai,
 rincian: 'Sleep & Energy OS — catat tidur, jam bangun, tingkat energi/fokus (1–5) + temuan pola waktu produktif',
 catatan: '\'Energi & jam produktif\' menempel pada catatan tidur yang sudah ada (energi 1-5, fokus 1-5, jam paling produktif diisi pengguna — bukan tebakan mesin); setelah 14 hari muncul pola (rata energi/fokus, jam produktif tersering) beserta dasar datanya; sebelum itu layar menjelaskan kenapa belum bisa. Uji: mesin + layar.',
    rute: '/kesehatan/energi',

  ),
  ButirFitur(
    id: 'FR-85',
 nama: 'Progress & konsistensi tanpa skor moral',
    modul: '3 · Aksi & Tujuan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'konsistensi mingguan tanpa skor moral.',
 rincian: 'Progress & konsistensi tanpa skor moral — ringkasan "tercatat / belum tercatat", grafik mingguan',
  ),
  ButirFitur(
    id: 'FR-86',
 nama: 'Jadwal Sholat',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 rincian: 'Jadwal Sholat — 5 waktu sesuai lokasi; pilih lokasi otomatis atau kota manual; pilih metode perhitungan, konvensi Ashar (madhhab), dan penyesuaian menit',
    rute: '/ibadah/jadwal-sholat',
  ),
  ButirFitur(
    id: 'FR-87',
 nama: 'Adzan & Pengingat Sholat',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 catatan: 'pengingat 5 waktu (bawaan mati, bisa dinyalakan), mode sebelum/tepat/sesudah + geser menit. Uji 20/20.',
 rincian: 'Adzan & Pengingat Sholat — mode: adzan, 5 menit sebelum, saat masuk waktu, pengingat setelah waktu berjalan + pilihan suara/dering',
  ),
  ButirFitur(
    id: 'FR-88',
 nama: 'Pelacakan Sholat 5 Waktu',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 rincian: 'Pelacakan Sholat 5 Waktu — tombol cepat ✓ per waktu; status "selesai / belum tercatat"',
  ),
  ButirFitur(
    id: 'FR-89',
 nama: 'Riwayat & Konsistensi Sholat',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'Terverifikasi 21 Sep: rekap mingguan/bulanan per waktu; angka dibandingkan dengan data mentah di uji lama; label \'tercatat\'.',
 rincian: 'Riwayat & Konsistensi Sholat — rekap mingguan/bulanan per waktu (mis. "Subuh 24/30 tercatat"), bukan skor keimanan',
    rute: '/ibadah/rekap',
  ),
  ButirFitur(
    id: 'FR-90',
 nama: 'Kalender Hijriah',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V1.5',
    status: StatusFitur.selesai,
 rincian: 'Kalender Hijriah — tanggal Hijriah + hari besar, dengan pilihan acuan kalender (mis. rujukan resmi negara/pilihan pengguna)',
    rute: '/ibadah/kalender-hijriah',
  ),
  ButirFitur(
    id: 'FR-91',
 nama: 'Ramadan Mode',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /ibadah/ramadan',
 rincian: 'Ramadan Mode — dashboard otomatis saat Ramadan: imsak, subuh, maghrib, puasa hari ini, sholat, bacaan, sedekah',
  ),
  ButirFitur(
    id: 'FR-92',
 nama: 'Pelacakan Puasa',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /ibadah/puasa',
 rincian: 'Pelacakan Puasa — Ramadan, Senin-Kamis, Ayyamul Bidh, puasa sunnah lain, qadha, custom',
  ),
  ButirFitur(
    id: 'FR-93',
 nama: 'Pelacakan Quran',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /ibadah/quran + kartu progres di briefing pagi',
 rincian: 'Pelacakan Quran — bacaan, mendengar, hafalan, murajaah + target harian (mis. 1 halaman/hari)',
  ),
  ButirFitur(
    id: 'FR-94',
 nama: 'Pelacakan Hafalan (Hifz)',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'pelacakan hafalan per juz/surah + status + jadwal ulangan versi pengguna.',
 rincian: 'Pelacakan Hafalan (Hifz) — per juz/surah: baru, murajaah, perlu diulang',
    rute: '/ibadah/hifz',
  ),
  ButirFitur(
    id: 'FR-95',
 nama: 'Dzikir & Doa',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /ibadah/dzikir; 4 adhkar pagi bisa ditandai dari layar Dzikir',
 rincian: 'Dzikir & Doa — pagi, petang, sebelum tidur + penghitung (mis. target 100, tercatat 67)',
  ),
  ButirFitur(
    id: 'FR-96',
 nama: 'Zakat & Sedekah',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'catatan infaq/sedekah + asisten hitung zakat (nisab 85 gram emas dari harga yang diisi pengguna, haul 354 hari, asumsi terbuka).',
 rincian: 'Zakat & Sedekah — catatan infaq/sadaqah + asisten perhitungan zakat (aset, acuan nisab, pelacakan haul) sebagai alat bantu, bukan keputusan',
    rute: '/ibadah/zakat',
  ),
  ButirFitur(
    id: 'FR-97',
 nama: 'Rencana Haji & Umrah',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V3',
    status: StatusFitur.selesai,
 rincian: 'Rencana Haji & Umrah — target dana (terhubung Goal & Finance), daftar persiapan dokumen',
 catatan: '\'Rencana haji & umrah\' menyimpan target dana + daftar persiapan dokumen; progres menampilkan persen tercapai, sisa, dan setoran per bulan sampai tanggal target, lengkap dengan peringatan bila target belum diisi / tanggal sudah lewat / setoran tidak realistis. Tabel baru rencana_ibadah & persiapan_ibadah ikut mesin sinkron 150. Uji: mesin + repositori + layar.',
    rute: '/ibadah/rencana',

  ),
  ButirFitur(
    id: 'FR-98',
 nama: 'Arah Kiblat & Masjid Terdekat',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V3',
    status: StatusFitur.selesai,
 rincian: 'Arah Kiblat & Masjid Terdekat — kompas dengan kalibrasi + cadangan arah mata angin bila sensor tidak layak; daftar masjid terdekat',
 catatan: '\'Arah kiblat & masjid terdekat\' menghitung arah kiblat dari koordinat (dengan peringatan kalibrasi); bila sensor kompas tidak ada / izin ditolak, layar TIDAK menampilkan angka palsu - hanya derajat + arah mata angin + kalimat sensor tidak tersedia. Pencarian masjid via Overpass disimpan (sumber + waktu) sehingga tetap terbaca offline; kegagalan jaringan dilaporkan apa adanya dan data lama tetap dipakai. Kanal kompas Android (KanalKompas.kt) + uji tirus. Uji: mesin + repositori + layar.',
    rute: '/ibadah/kiblat',

  ),
  ButirFitur(
    id: 'FR-99',
 nama: 'Islamic Morning Briefing (signature)',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'kartu ibadah pagi di briefing: sapaan, progres Quran, 4 adhkar; 3 uji',
 rincian: 'Islamic Morning Briefing (signature) — Assalamualaikum, tanggal Hijriah, waktu sholat berikutnya + hitung mundur, target Quran, adhkar, agenda hari ini',
  ),
  ButirFitur(
    id: 'FR-100',
 nama: 'Islamic Evening Review & Muhasabah',
    modul: '4 · Ibadah (Islamic OS)',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /ibadah/muhasabah',
 rincian: 'Islamic Evening Review & Muhasabah — rekap ibadah hari ini + daftar refleksi (bukan penilaian): sholat terjaga, mengingat Allah, membantu orang, menghindari hal yang disesali, belajar, bersyukur + kol',
  ),
  ButirFitur(
    id: 'FR-101',
 nama: 'Health Dashboard (tren)',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /kesehatan',
 rincian: 'Health Dashboard (tren) — berat, tekanan darah, tidur, langkah, air, olahraga, suasana hati + arah naik/turun dibanding periode sebelumnya',
  ),
  ButirFitur(
    id: 'FR-102',
 nama: 'Pencatat Aktivitas',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /kesehatan/aktivitas',
 rincian: 'Pencatat Aktivitas — jalan, lari, sepeda, renang, gym, peregangan, olahraga, aktivitas rumah (durasi/jarak)',
  ),
  ButirFitur(
    id: 'FR-103',
 nama: 'Pencatat Tidur',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /kesehatan/tidur',
 rincian: 'Pencatat Tidur — jam tidur, jam bangun, durasi, kualitas, tidur siang',
  ),
  ButirFitur(
    id: 'FR-104',
 nama: 'Berat & Ukuran Tubuh',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'berat & ukuran tubuh — IMT dengan ambang umum, target & tren 30 hari.',
 rincian: 'Berat & Ukuran Tubuh — berat, lingkar perut, lemak tubuh, IMT, massa otot, detak jantung istirahat + target',
    rute: '/kesehatan/ukuran-tubuh',
  ),
  ButirFitur(
    id: 'FR-105',
 nama: 'Jurnal Kesehatan (angka)',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'jurnal angka kesehatan — tekanan darah 2 angka, satuan per jenis, tren 30 hari.',
 rincian: 'Jurnal Kesehatan (angka) — tekanan darah, detak jantung, gula darah, suhu, saturasi oksigen, kolesterol, hasil lab + catatan satuan',
    rute: '/kesehatan/jurnal-angka',
  ),
  ButirFitur(
    id: 'FR-106',
 nama: 'Manajer Obat & Vitamin',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /kesehatan/obat + penanda minum',
 rincian: 'Manajer Obat & Vitamin — jadwal minum (jam & jumlah) + penanda "sudah diminum"',
  ),
  ButirFitur(
    id: 'FR-107',
 nama: 'Perkiraan Obat Habis & Pengingat Beli',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'perkiraan obat habis (sisa ÷ dosis per hari) + pengingat H-5/H-1.',
 rincian: 'Perkiraan Obat Habis & Pengingat Beli — sisa tablet, perkiraan tanggal habis, pengingat membeli',
    rute: '/kesehatan/obat',
  ),
  ButirFitur(
    id: 'FR-108',
 nama: 'Brankas Catatan Medis',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'brankas catatan medis — jenis (lab, tahunan, resep, imunisasi, tagihan medis, dokter, pencitraan), pencarian kata menjangkau judul/hasil/ringkasan/tenaga kesehatan/fasilitas + lampiran berkas TERENKRIPSI (AES-256-GCM, kunci di Android Keystore, tidak diekspor). Bila perangkat tidak mendukung enkripsi, berkas TIDAK disimpan.',
 rincian: 'Brankas Catatan Medis — hasil lab, pemeriksaan tahunan, resep, imunisasi, tagihan medis, catatan dokter, laporan pencitraan + pencarian',
    rute: '/kesehatan/catatan-medis',
  ),
  ButirFitur(
    id: 'FR-109',
 nama: 'Janji Dokter di Kalender',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'janji dokter/lab/kontrol + pengingat 7 hari, 1 hari, dan 2 jam sebelum.',
 rincian: 'Janji Dokter di Kalender — pemeriksaan, tes lab, kontrol + pengingat 7 hari/1 hari/2 jam',
    rute: '/kesehatan/janji',
  ),
  ButirFitur(
    id: 'FR-110',
 nama: 'Catatan Makan Ringkas (quick log)',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'catat cepat per waktu makan, porsi, dan penilaian sendiri (baik/cukup/kurang).',
 rincian: 'Catatan Makan Ringkas (quick log) — per waktu makan, daftar sederhana + penilaian mutu (baik/cukup/kurang)',
    rute: '/kesehatan/makan',
  ),
  ButirFitur(
    id: 'FR-111',
 nama: 'Pencatat Air',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'tombol +250 ml / +500 ml',
 rincian: 'Pencatat Air — target harian + tombol +250 ml / +500 ml',
  ),
  ButirFitur(
    id: 'FR-112',
 nama: 'Jurnal Suasana Hati & Stres',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'suasana hati, energi & stres 1-5, pemicu, catatan; rata-rata & arah 14 hari.',
 rincian: 'Jurnal Suasana Hati & Stres — pilihan suasana hati, tingkat energi & stres (1–5), catatan bebas',
    rute: '/kesehatan/suasana',
  ),
  ButirFitur(
    id: 'FR-113',
 nama: 'Mesin Temuan Kesehatan (insight)',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'temuan dihitung dari angka sendiri (berat, tekanan, tidur, air, suasana) + angka pendukung; bukan diagnosis.',
 rincian: 'Mesin Temuan Kesehatan (insight) — menghubungkan tidur ↔ suasana hati ↔ aktivitas ↔ berat, dalam bahasa netral',
    rute: '/kesehatan/temuan',
  ),
  ButirFitur(
    id: 'FR-114',
 nama: 'Peringatan Dini (watch)',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'peringatan dini dari catatan sendiri — berat naik N minggu, tidur di bawah kebiasaan, aktivitas menurun 14 hari, sistolik naik; ambang bisa diatur & tersimpan; tiap peringatan memuat saran netral tanpa kata menghakimi, disertai catatan \'bukan diagnosis\'.',
 rincian: 'Peringatan Dini (watch) — mis. berat naik 4 minggu berturut-turut, tidur di bawah kebiasaan, aktivitas menurun 14 hari',
    rute: '/kesehatan/peringatan-dini',
  ),
  ButirFitur(
    id: 'FR-115',
 nama: 'Mode Kunjungan Dokter',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'mode kunjungan dokter — ringkasan 30 hari (berat, tekanan, tidur, aktivitas, suasana, keluhan) jadi SATU halaman PDF; angkanya dihitung dari fungsi yang sama dengan layar sehingga identik dengan data aplikasi.',
 rincian: 'Mode Kunjungan Dokter — satu halaman ringkasan 30 hari (berat, tekanan darah, tidur, aktivitas, suasana hati, keluhan) yang bisa dicetak',
    rute: '/kesehatan/kunjungan',
  ),
  ButirFitur(
    id: 'FR-116',
 nama: 'Laporan Kesehatan Bulanan',
    modul: '5 · Kesehatan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'laporan bulanan + tiga kelompok: membaik / berubah / perlu diperhatikan.',
 rincian: 'Laporan Kesehatan Bulanan — perubahan berat/aktivitas/tidur/air/kebiasaan + "yang membaik, yang berubah, yang perlu perhatian"',
    rute: '/kesehatan/laporan-bulanan',
  ),
  ButirFitur(
    id: 'FR-117',
 nama: 'Profil Kesehatan & Kartu Darurat',
    modul: '5 · Kesehatan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'profil kesehatan (golongan darah, alergi, kondisi, obat penting, kontak darurat) + kartu darurat OFFLINE; pintasan Android membuka kartu langsung dari layar kunci (setShowWhenLocked) sementara rincian sensitif hanya tampil setelah perangkat dibuka.',
 rincian: 'Profil Kesehatan & Kartu Darurat — profil (golongan darah, alergi, kondisi, obat, kontak darurat) + kartu darurat yang bisa dibuka tanpa internet & tanpa membuka seluruh aplikasi',
    rute: '/kesehatan/profil-kesehatan',
  ),
  ButirFitur(
    id: 'FR-118',
 nama: 'Catatan & Ide',
    modul: '6 · Pengetahuan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'catatan, kategori, tag, sematan, arsip, pencarian + LAMPIRAN foto & rekaman suara (kanal Android sendiri, tanpa paket tambahan; berkas disimpan di folder aplikasi).',
 rincian: 'Catatan & Ide — simpan catatan, kutipan, tautan, foto, rekaman suara, tag; pencarian cepat',
    rute: '/pengetahuan/catatan',
  ),
  ButirFitur(
    id: 'FR-119',
 nama: 'Jurnal Keputusan (Decision OS)',
    modul: '6 · Pengetahuan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'keputusan + pilihan/alasan/risiko/biaya/keyakinan, tinjauan hasil 3/6/12 bulan.',
 rincian: 'Jurnal Keputusan (Decision OS) — keputusan: pilihan, alasan, risiko, biaya, hasil yang diharapkan, tenggat keputusan, keputusan final, tinjauan hasil 3/6/12 bulan',
    rute: '/pengetahuan/keputusan',
  ),
  ButirFitur(
    id: 'FR-120',
 nama: 'Pelacakan Pembelajaran',
    modul: '6 · Pengetahuan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'topik, sumber, menit, tahap belajar + grafik 14 hari.',
 rincian: 'Pelacakan Pembelajaran — kursus, keahlian, jam belajar, tingkat penguasaan',
    rute: '/pengetahuan/pembelajaran',
  ),
  ButirFitur(
    id: 'FR-121',
 nama: 'Pengulangan Berkala (spaced repetition)',
    modul: '6 · Pengetahuan',
    fase: 'V4',
    status: StatusFitur.selesai,
 catatan: 'jadwal ulangan 1/3/7/16/35/90/180 hari dihitung dari jawaban sendiri.',
 rincian: 'Pengulangan Berkala (spaced repetition) — jadwal ulangan untuk hafalan/kosakata/istilah',
    rute: '/pengetahuan/ulangan',
  ),
  ButirFitur(
    id: 'FR-122',
 nama: 'Pelacakan Buku & Bacaan',
    modul: '6 · Pengetahuan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'daftar baca, progres halaman, status, catatan & penilaian sendiri.',
 rincian: 'Pelacakan Buku & Bacaan — daftar baca, sedang dibaca, selesai + catatan & kutipan',
    rute: '/pengetahuan/bacaan',
  ),
  ButirFitur(
    id: 'FR-123',
 nama: 'Penghubung Pengetahuan',
    modul: '6 · Pengetahuan',
    fase: 'V4',
    status: StatusFitur.selesai,
 catatan: 'tautan catatan/keputusan/bacaan/kartu/pembelajaran dengan tujuan, proyek, tugas, dokumen.',
 rincian: 'Penghubung Pengetahuan — tautkan catatan ↔ tujuan ↔ proyek ↔ tugas ↔ dokumen',
    rute: '/pengetahuan/tautan',
  ),
  ButirFitur(
    id: 'FR-124',
 nama: 'Daftar Aset',
    modul: '7 · Rumah & Aset',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'daftar aset fisik (rumah, kendaraan, perangkat, furnitur, elektronik) — tanggal beli, harga, nomor seri, garansi, masa pakai, lokasi; total nilai tampil & ikut Kekayaan Bersih tanpa input ulang.',
 rincian: 'Daftar Aset — rumah, kendaraan, perangkat, furnitur, elektronik: tanggal beli, harga, nomor seri, garansi',
    rute: '/rumah/aset',
  ),
  ButirFitur(
    id: 'FR-125',
 nama: 'Jadwal & Riwayat Perawatan Aset',
    modul: '7 · Rumah & Aset',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'jadwal perawatan terikat aset + riwayat perbaikan berbiaya (bisa dikaitkan ke pengeluaran), total & rata-rata per tahun, pengingat perawatan terpasang di isolate utama & latar.',
 rincian: 'Jadwal & Riwayat Perawatan Aset — servis berkala (oli, AC, tandon, filter), riwayat perbaikan, biaya',
    rute: '/rumah/aset',
  ),
  ButirFitur(
    id: 'FR-126',
 nama: 'Garansi & Invoice',
    modul: '7 · Rumah & Aset',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'garansi per aset (tanggal berakhir) + status aktif/segera berakhir/berakhir; yang berakhir <= 30 hari muncul sebagai Perhatian di Today.',
 rincian: 'Garansi & Invoice — lampiran berkas/struk per aset + pengingat berakhirnya garansi',
    rute: '/rumah/aset',
  ),
  ButirFitur(
    id: 'FR-127',
 nama: 'Perkiraan Umur Pakai & Penggantian',
    modul: '7 · Rumah & Aset',
    fase: 'V4',
    status: StatusFitur.selesai,
 catatan: 'perkiraan umur pakai & waktu penggantian dari tanggal beli + masa pakai, lengkap dengan DASAR perhitungan & saran dana per bulan (estimasi, bukan klaim).',
 rincian: 'Perkiraan Umur Pakai & Penggantian — estimasi masa guna + saran waktu pemeriksaan/penggantian',
    rute: '/rumah/aset',
  ),
  ButirFitur(
    id: 'FR-128',
 nama: 'Brankas Dokumen & Masa Berlaku',
    modul: '8 · Dokumen',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'dengan catatan (daftar + masa berlaku + nama berkas; enkripsi berkas BELUM — layar menuliskan itu apa adanya',
 rincian: 'Brankas Dokumen & Masa Berlaku — KTP, KK, paspor, SIM, STNK, sertifikat, ijazah, kontrak, polis, dokumen anak + tanggal berlaku/ perpanjangan',
    rute: '/dokumen',
  ),
  ButirFitur(
    id: 'FR-129',
 nama: 'Pengingat Perpanjangan Berlapis',
    modul: '8 · Dokumen',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'lead 90/30/7/1 hari, bisa diubah; terdaftar di isolate utama & latar',
 rincian: 'Pengingat Perpanjangan Berlapis — H-90 / H-30 / H-7 / H-1 + tombol "sudah diperpanjang" yang memperbarui masa berlaku',
  ),
  ButirFitur(
    id: 'FR-130',
 nama: 'Salin Cepat & Bagikan Terkendali',
    modul: '8 · Dokumen',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'salin nomor sekali ketuk + bagikan tersamar — nomor disamarkan, berkas asli hanya ikut bila pengguna mencentangnya sendiri dan berkasnya ada.',
 rincian: 'Salin Cepat & Bagikan Terkendali — salin nomor paspor/KTP/KK tanpa membuka galeri; bagikan satu berkas dengan penyamaran bagian sensitif',
    rute: '/dokumen',
  ),
  ButirFitur(
    id: 'FR-131',
 nama: 'Anggota Keluarga & Tanggung Jawab',
    modul: '9 · Keluarga',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'anggota keluarga + pemilik & penanggung jawab per item (contoh: tagihan sekolah milik anak, ditanggung pasangan); saringan per anggota bekerja; anggota bertanda pribadi hanya tampil setelah perangkat dibuka.',
 rincian: 'Anggota Keluarga & Tanggung Jawab — tiap item punya pemilik & penanggung jawab (mis. tagihan sekolah: pemilik anak, penanggung jawab pasangan)',
    rute: '/keluarga',
  ),
  ButirFitur(
    id: 'FR-132',
 nama: 'Kalender Keluarga',
    modul: '9 · Keluarga',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'kalender keluarga — satu tampilan agenda semua anggota (tagihan, tugas, janji kesehatan, jadwal perawatan, ulang tahun) dengan WARNA BERBEDA per anggota; saringan per anggota; warna ditetapkan dari urutan anggota sehingga tidak pernah sama.',
 rincian: 'Kalender Keluarga — agenda bersama, ulang tahun, anniversary, kegiatan sekolah anak dalam satu tampilan',
  ),
  ButirFitur(
    id: 'FR-133',
 nama: 'Kas & Tanggung Jawab Rumah Tangga',
    modul: '9 · Keluarga',
    fase: 'V3',
    status: StatusFitur.selesai,
 rincian: 'Kas & Tanggung Jawab Rumah Tangga — "siapa bayar apa", pengingat halus satu ketukan, catatan pelunasan',
 catatan: '\'Kas & tanggung jawab rumah tangga\' mencatat siapa bayar apa (pemilik, penanggung jawab, jatuh tempo) + riwayat pelunasan; ringkasan per anggota; pengingat halus SATU KETUKAN hanya boleh terkirim bila pengguna menyalakan izin (saklar di tabel pengaturan), maksimal sekali sehari, pada jam wajar 08.00-21.00 - kalau tidak, layar menyebut alasannya. Tabel tanggung_jawab_rumah ikut mesin sinkron 150. Uji: mesin + repositori + layar.',
    rute: '/rumah-tangga',

  ),
  ButirFitur(
    id: 'FR-134',
 nama: 'Perencanaan Perjalanan',
    modul: '10 · Perjalanan',
    fase: 'V4',
    status: StatusFitur.selesai,
 rincian: 'Perencanaan Perjalanan — itinerary, tiket, hotel, anggaran, daftar bawaan, dokumen, pengingat keberangkatan',
 catatan: '\'Perencanaan perjalanan\' menyatukan jadwal + anggaran + dokumen dalam satu perjalanan: agenda/tiket/hotel/dokumen/daftar bawaan; realisasi anggaran dihitung dari transaksi keuangan yang bertaut perjalanan (tanpa input ulang); pengingat keberangkatan H-7/H-1/H-0 sebagai sumber pengingat tambahan. Tabel perjalanan & item_perjalanan ikut mesin sinkron 150. Uji: mesin + repositori + layar.',
    rute: '/perjalanan',

  ),
  ButirFitur(
    id: 'FR-135',
 nama: 'Jurnal Perjalanan',
    modul: '10 · Perjalanan',
    fase: 'V4',
    status: StatusFitur.selesai,
 rincian: 'Jurnal Perjalanan — foto, pengeluaran, tempat, penilaian, kenangan',
 catatan: '\'Jurnal perjalanan\' menyimpan cerita + foto + penilaian per hari; SETIAP pengeluaran yang dicatat langsung menjadi transaksi di laporan keuangan (tanpa input ulang) dan ditandai di layar; catatan lama yang belum bertaut transaksi dilaporkan apa adanya (bukan disembunyikan). Tabel catatan_perjalanan ikut mesin sinkron 150. Uji: mesin + repositori + layar.',
    rute: '/perjalanan (jurnal di dalam perjalanan)',

  ),
  ButirFitur(
    id: 'FR-136',
 nama: 'Backup & Restore penuh',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'format cadangan otomatis mencakup 23 tabel baru v4; skema lebih baru ditolak',
 rincian: 'Backup & Restore penuh — JSON + berkas lampiran, dengan pratinjau isi backup sebelum restore',
  ),
  ButirFitur(
    id: 'FR-137',
 nama: 'Cadangan Otomatis + Rotasi + Cek Integritas',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'dengan catatan (saklar bawaan MATI; berjalan saat aplikasi dibuka, bukan penjadwal OS; rotasi hanya menghapus berkas yang dicatatnya sendiri; 10 uji',
 rincian: 'Cadangan Otomatis + Rotasi + Cek Integritas — cadangan berkala, simpan N salinan terakhir, periksa keutuhan database',
  ),
  ButirFitur(
    id: 'FR-138',
 nama: 'Audit Log Pengguna',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'catatan aktivitas mencakup uang, kategori, langganan, kesehatan.',
 rincian: 'Audit Log Pengguna — catatan perubahan penting: "22:31 tagihan #18 ditandai lunas", "nominal diubah 300.000 → 325.000", "pengingat ditunda sampai 23:30"',
    rute: '/audit',
  ),
  ButirFitur(
    id: 'FR-139',
 nama: 'Search Everything (signature)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'satu kotak cari lintas tabel; rute /cari; 15 uji',
 rincian: 'Search Everything (signature) — satu kotak mencari tagihan, pembayaran, tugas, catatan, dokumen, jurnal, janji',
  ),
  ButirFitur(
    id: 'FR-140',
 nama: 'Life Timeline (signature)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'lini masa hidup (signature) — kejadian dari 14 sumber data tersusun per bulan, dapat dicari & disaring per modul, tiap baris menyebut asal datanya (mis. tugas#12), plus rangkuman \'apa yang terjadi bulan ini\'.',
 rincian: 'Life Timeline (signature) — seluruh kejadian hidup tersusun per hari/bulan/tahun, dapat dicari & disaring per modul',
  ),
  ButirFitur(
    id: 'FR-141',
 nama: 'Personal Analytics',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'analitik pribadi lintas modul untuk 7/30/90 hari & 1 tahun; SETIAP angka menampilkan baris sumber (tabel & rentangnya) sehingga tidak ada angka misterius.',
 rincian: 'Personal Analytics — ringkasan lintas modul untuk 7/30/90 hari dan 1 tahun',
  ),
  ButirFitur(
    id: 'FR-142',
 nama: 'Smart Insights',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.selesai,
 rincian: 'Smart Insights — temuan lintas modul: pengeluaran menyimpang, langganan jarang dipakai, titik saldo terendah, sebaran jatuh tempo ("73% tagihan jatuh pada minggu terakhir")',
 catatan: '\'Temuan pintar\' menyusun temuan dari data nyata (pengeluaran bulanan, sebaran jatuh tempo, langganan jarang dipakai, titik saldo terendah); SETIAP temuan menuliskan dasar data + periode yang dipakai, dan temuan hanya muncul bila datanya cukup — sisanya masuk daftar \'belum bisa\' beserta alasannya. Bila belum ada pergerakan uang sama sekali, temuan saldo tidak dibuat (tidak menyesatkan). Uji: mesin + layar.',
    rute: '/temuan-pintar',

  ),
  ButirFitur(
    id: 'FR-143',
 nama: 'Forecast',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.selesai,
 rincian: 'Forecast — proyeksi saldo beberapa bulan, perkiraan keterlambatan proyek, tabrakan tenggat',
 catatan: '\'Ramalan saldo\' memakai asumsi yang ditulis terbuka (laba bulanan rata-rata, simpangan harian aktual, tagihan tetap & langganan) dan menampilkan RENTANG tiga angka tiap bulan (pesimis/tengah/optimis) — bukan satu angka mutlak; bulan yang bisa minus ditandai + saran menggeser apa. Uji: mesin + layar.',
    rute: '/ramalan-saldo',

  ),
  ButirFitur(
    id: 'FR-144',
 nama: 'Weekly Life Review',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'tinjauan pekan per 6 pilar (uang, kesehatan, tujuan & tugas, pengetahuan, ibadah, rumah & aset) membandingkan pekan ini vs pekan lalu dengan angka pendukung; tiga kolom isian tersimpan; teks ringkas bisa disalin untuk notifikasi; pengingat Minggu malam otomatis DILEWATI bila pekan itu sudah diisi.',
 rincian: 'Weekly Life Review — rekap mingguan per pilar: apa yang membaik, apa yang perlu perhatian, fokus minggu depan',
  ),
  ButirFitur(
    id: 'FR-145',
 nama: 'Monthly Life Report (signature)',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V3',
    status: StatusFitur.selesai,
 catatan: 'laporan bulanan (signature) — keuangan, tagihan, tujuan, tugas, langganan, kekayaan bersih + \'membaik / berubah / perlu perhatian\'; bisa diarsipkan (angka kunci tersimpan sebagai JSON untuk pembanding bulan berikutnya) dan dibagikan sebagai PDF.',
 rincian: 'Monthly Life Report (signature) — laporan bulanan: keuangan, tagihan, tujuan, tugas, langganan, kekayaan bersih + "apa yang membaik / berubah / perlu perhatian"',
  ),
  ButirFitur(
    id: 'FR-146',
 nama: 'Annual Life Review',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.selesai,
 rincian: 'Annual Life Review — "Your Year in Life": capaian, kebiasaan, keuangan, kesehatan, ibadah',
 catatan: '\'Tinjauan tahun\' merangkum tahun berjalan per pilar (uang, kesehatan, ibadah, hubungan, pengetahuan) dari data nyata; hanya tampil bila data mencakup minimal 6 bulan — kalau kurang, layar menyebut berapa bulan data yang ada dan tidak mengarang hasil. Uji: mesin + layar.',
    rute: '/tinjauan-tahun',

  ),
  ButirFitur(
    id: 'FR-147',
 nama: 'Notification Center',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: 'rute /notifikasi: riwayat + tingkat + tanda selesai',
 rincian: 'Notification Center — riwayat notifikasi dengan tingkat (mendesak/penting/biasa) + tanda selesai',
  ),
  ButirFitur(
    id: 'FR-148',
 nama: 'Snooze & Reschedule Engine',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
 catatan: '15 menit/1 jam/3 jam/besok 09:00; tercatat di audit',
 rincian: 'Snooze & Reschedule Engine — 15 menit, 1 jam, 3 jam, besok, akhir pekan, kustom; jatuh tempo asli tidak berubah',
  ),
  ButirFitur(
    id: 'FR-149',
 nama: 'AI Copilot ber-konteks',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.selesai,
 rincian: 'AI Copilot ber-konteks — tanya jawab atas data sendiri ("apa yang harus saya prioritaskan besok?"), dengan izin eksplisit & penjelasan data apa yang dikirim',
 catatan: 'jawaban memakai HANYA data pengguna sendiri '
        '(tagihan belum lunas, dana persiapan, jadwal obat, perjalanan '
        'terdekat). Butuh izin eksplisit + kunci API milik pengguna; layar '
        'menampilkan daftar data yang akan dikirim sebelum tombol Tanya. Tanpa '
        'izin / kunci / alamat benar / saat offline → fitur MATI dengan alasan '
        'jelas. Jawaban layanan AI diuraikan apa adanya (401/429/5xx '
        'dibedakan). Uji: mesin + repositori + layar, tanpa jaringan sungguhan.',
    rute: '/copilot',
  ),
  ButirFitur(
    id: 'FR-150',
 nama: 'Sinkron Antar Perangkat & Cloud',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.selesai,
 catatan: 'sinkron SEMUA MODUL (40 tabel: uang, aset, tujuan/tugas, kebiasaan, kesehatan, dokumen, pengetahuan, ibadah) — pengenal uid, kaitan antar tabel dipetakan ulang antar HP, bentrok versi-kalah disimpan, diuji dua basis data. Belum: berkas lampiran & catatan obat.',
 rincian: 'Sinkron Antar Perangkat & Cloud — sinkron opsional, terenkripsi, pilihan penyedia atau server sendiri',
    rute: '/akun',
  ),
  ButirFitur(
    id: 'FR-151',
 nama: 'Widget & Akses Cepat Lanjutan',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V2',
    status: StatusFitur.selesai,
 rincian: 'Widget & Akses Cepat Lanjutan — widget Today interaktif (aksi langsung), aksi cepat ikon, tombol panel cepat',
 catatan: 'tombol di widget LANGSUNG menjalankan aksi saat aplikasi terbuka dari widget (satu ketukan, bukan membuka formulir lagi) dan menulis ke basis data yang sama sehingga tersinkron; baris widget bisa ditandai lunas satu per satu; aksi cepat ikon bertambah: \'Catat pengeluaran\' dan \'Widget tagihan\'. Uji: aksi lunas benar-benar mengubah data.',
    rute: '/pengaturan/ikon-widget',

  ),
  ButirFitur(
    id: 'FR-152',
 nama: 'Multi-bahasa & Multi-mata Uang',
    modul: '11 · Platform & Kecerdasan',
    fase: 'V4',
    status: StatusFitur.selesai,
 rincian: 'Multi-bahasa & Multi-mata Uang — Indonesia, Melayu, Inggris + Rupiah/Ringgit/USD',
 catatan: 'multi-bahasa (Indonesia/Melayu/Inggris) untuk kerangka aplikasi, Pengaturan, dan tab; kurs selalu disimpan bersama SUMBER + WAKTU pembaruan, bisa diambil dari jaringan atau diisi manual, dan setiap nilai yang belum punya kurs disebut belum bisa dikonversi (tidak dikira-kira). Uji: mesin + repositori + layar.',
    rute: 'Pengaturan (bahasa & kurs)',

  ),
];

/// Ringkasan jumlah per status (dihitung dari daftar di atas).
Map<StatusFitur, int> ringkasanPetaFitur() {
  final hasil = <StatusFitur, int>{
    StatusFitur.selesai: 0,
    StatusFitur.sebagian: 0,
    StatusFitur.belum: 0,
  };
  for (final b in petaFitur) {
    hasil[b.status] = (hasil[b.status] ?? 0) + 1;
  }
  return hasil;
}

